#!/bin/bash
set -e
cd /home/miyamii/clownfish_microarchitecture/hierarchical_synth
echo "======================================================"
echo "Started: $(date)"
YOSYS="/usr/bin/yosys"
echo "[1/17] simple_alu..."
$YOSYS -s synth_simple_alu.ys > simple_alu.log 2>&1 && echo "  ✓"
echo "[2/17] complex_alu..."
$YOSYS -s synth_complex_alu.ys > complex_alu.log 2>&1 && echo "  ✓"
echo "[3/17] mul_div..."
$YOSYS -s synth_mul_div_unit.ys > mul_div.log 2>&1 && echo "  ✓"
echo "[4/17] FPU (30-60 min)..."
$YOSYS -s synth_fpu_unit.ys > fpu.log 2>&1 && echo "  ✓"
echo "[5/17] Vector (30-60 min)..."
$YOSYS -s synth_vector_unit.ys > vector.log 2>&1 && echo "  ✓"
echo "[6/17] LSU..."
$YOSYS -s synth_lsu.ys > lsu.log 2>&1 && echo "  ✓"
echo "[7/17] gshare..."
$YOSYS -s synth_gshare_predictor.ys > gshare.log 2>&1 && echo "  ✓"
echo "[8/17] bimodal..."
$YOSYS -s synth_bimodal_predictor.ys > bimodal.log 2>&1 && echo "  ✓"
echo "[9/17] tournament..."
$YOSYS -s synth_tournament_selector.ys > tournament.log 2>&1 && echo "  ✓"
echo "[10/17] BTB..."
$YOSYS -s synth_btb.ys > btb.log 2>&1 && echo "  ✓"
echo "[11/17] RAS..."
$YOSYS -s synth_ras.ys > ras.log 2>&1 && echo "  ✓"
echo "[12/17] register_rename..."
$YOSYS -s synth_register_rename.ys > register_rename.log 2>&1 && echo "  ✓"
echo "[13/17] reservation_station..."
$YOSYS -s synth_reservation_station.ys > reservation_station.log 2>&1 && echo "  ✓"
echo "[14/17] ROB (30-45 min)..."
$YOSYS -s synth_reorder_buffer.ys > reorder_buffer.log 2>&1 && echo "  ✓"
echo "[15/17] L1 I-cache (30-45 min)..."
$YOSYS -s synth_l1_icache.ys > l1_icache.log 2>&1 && echo "  ✓"
echo "[16/17] L1 D-cache (30-45 min)..."
$YOSYS -s synth_l1_dcache_new.ys > l1_dcache.log 2>&1 && echo "  ✓"
echo "[17/17] L2 cache (60-120 MIN!)..."
$YOSYS -s synth_l2_cache_new.ys > l2_cache.log 2>&1 && echo "  ✓"
echo "DONE: $(date)"
ls -lh *_synth.v
