/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module complex_alu(clk, rst_n, valid_i, operand_a_i, operand_b_i, pc_i, imm_i, op_i, rob_id_i, phys_dest_i, valid_o, result_o, branch_target_o, branch_taken_o, rob_id_o, phys_dest_o, exception_o, ready_o);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire [3:0] _0004_;
  wire [3:0] _0005_;
  wire [3:0] _0006_;
  wire [3:0] _0007_;
  wire [3:0] _0008_;
  wire [3:0] _0009_;
  wire [3:0] _0010_;
  wire [3:0] _0011_;
  wire [3:0] _0012_;
  wire [3:0] _0013_;
  wire [3:0] _0014_;
  wire [3:0] _0015_;
  wire [3:0] _0016_;
  wire [3:0] _0017_;
  wire [3:0] _0018_;
  wire [3:0] _0019_;
  wire [3:0] _0020_;
  wire [3:0] _0021_;
  wire [1:0] _0022_;
  wire _0023_;
  wire [3:0] _0024_;
  wire [1:0] _0025_;
  wire _0026_;
  wire [2:0] _0027_;
  wire [1:0] _0028_;
  wire [1:0] _0029_;
  wire [15:0] _0030_;
  wire [7:0] _0031_;
  wire [3:0] _0032_;
  wire [1:0] _0033_;
  wire [2:0] _0034_;
  wire [1:0] _0035_;
  wire [1:0] _0036_;
  wire [1:0] _0037_;
  wire [1:0] _0038_;
  wire [1:0] _0039_;
  wire [1:0] _0040_;
  wire [15:0] _0041_;
  wire [7:0] _0042_;
  wire [3:0] _0043_;
  wire [1:0] _0044_;
  wire [3:0] _0045_;
  wire [3:0] _0046_;
  wire [3:0] _0047_;
  wire [3:0] _0048_;
  wire [3:0] _0049_;
  wire [3:0] _0050_;
  wire [3:0] _0051_;
  wire [3:0] _0052_;
  wire [3:0] _0053_;
  wire [3:0] _0054_;
  wire [3:0] _0055_;
  wire [3:0] _0056_;
  wire [3:0] _0057_;
  wire [3:0] _0058_;
  wire _0059_;
  wire [31:0] _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire [287:0] _0070_;
  wire [287:0] _0071_;
  wire [8:0] _0072_;
  wire [31:0] _0073_;
  wire _0074_;
  wire [63:0] _0075_;
  wire [63:0] _0076_;
  wire [1:0] _0077_;
  wire [31:0] _0078_;
  wire _0079_;
  wire [31:0] _0080_;
  wire [31:0] _0081_;
  wire [31:0] _0082_;
  wire [31:0] _0083_;
  wire [31:0] _0084_;
  wire [31:0] _0085_;
  wire [31:0] _0086_;
  wire [31:0] _0087_;
  wire [31:0] _0088_;
  wire [31:0] _0089_;
  wire [31:0] _0090_;
  wire [31:0] _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  output branch_taken_o;
  wire branch_taken_o;
  output [31:0] branch_target_o;
  wire [31:0] branch_target_o;
  wire [31:0] calc_result;
  wire calc_taken;
  wire [31:0] calc_target;
  input clk;
  wire clk;
  output exception_o;
  wire exception_o;
  input [31:0] imm_i;
  wire [31:0] imm_i;
  input [3:0] op_i;
  wire [3:0] op_i;
  input [31:0] operand_a_i;
  wire [31:0] operand_a_i;
  input [31:0] operand_b_i;
  wire [31:0] operand_b_i;
  input [31:0] pc_i;
  wire [31:0] pc_i;
  input [6:0] phys_dest_i;
  wire [6:0] phys_dest_i;
  output [6:0] phys_dest_o;
  wire [6:0] phys_dest_o;
  output ready_o;
  wire ready_o;
  output [31:0] result_o;
  wire [31:0] result_o;
  input [5:0] rob_id_i;
  wire [5:0] rob_id_i;
  output [5:0] rob_id_o;
  wire [5:0] rob_id_o;
  input rst_n;
  wire rst_n;
  input valid_i;
  wire valid_i;
  output valid_o;
  wire valid_o;
  sky130_fd_sc_hd__dfrtp_1 _0373_ (
    .CLK(clk),
    .D(valid_i),
    .Q(valid_o),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0374_ (
    .CLK(clk),
    .D(calc_result[0]),
    .Q(result_o[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0375_ (
    .CLK(clk),
    .D(calc_result[1]),
    .Q(result_o[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0376_ (
    .CLK(clk),
    .D(calc_result[2]),
    .Q(result_o[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0377_ (
    .CLK(clk),
    .D(calc_result[3]),
    .Q(result_o[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0378_ (
    .CLK(clk),
    .D(calc_result[4]),
    .Q(result_o[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0379_ (
    .CLK(clk),
    .D(calc_result[5]),
    .Q(result_o[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0380_ (
    .CLK(clk),
    .D(calc_result[6]),
    .Q(result_o[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0381_ (
    .CLK(clk),
    .D(calc_result[7]),
    .Q(result_o[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0382_ (
    .CLK(clk),
    .D(calc_result[8]),
    .Q(result_o[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0383_ (
    .CLK(clk),
    .D(calc_result[9]),
    .Q(result_o[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0384_ (
    .CLK(clk),
    .D(calc_result[10]),
    .Q(result_o[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0385_ (
    .CLK(clk),
    .D(calc_result[11]),
    .Q(result_o[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0386_ (
    .CLK(clk),
    .D(calc_result[12]),
    .Q(result_o[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0387_ (
    .CLK(clk),
    .D(calc_result[13]),
    .Q(result_o[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0388_ (
    .CLK(clk),
    .D(calc_result[14]),
    .Q(result_o[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0389_ (
    .CLK(clk),
    .D(calc_result[15]),
    .Q(result_o[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0390_ (
    .CLK(clk),
    .D(calc_result[16]),
    .Q(result_o[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0391_ (
    .CLK(clk),
    .D(calc_result[17]),
    .Q(result_o[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0392_ (
    .CLK(clk),
    .D(calc_result[18]),
    .Q(result_o[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0393_ (
    .CLK(clk),
    .D(calc_result[19]),
    .Q(result_o[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0394_ (
    .CLK(clk),
    .D(calc_result[20]),
    .Q(result_o[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0395_ (
    .CLK(clk),
    .D(calc_result[21]),
    .Q(result_o[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0396_ (
    .CLK(clk),
    .D(calc_result[22]),
    .Q(result_o[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0397_ (
    .CLK(clk),
    .D(calc_result[23]),
    .Q(result_o[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0398_ (
    .CLK(clk),
    .D(calc_result[24]),
    .Q(result_o[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0399_ (
    .CLK(clk),
    .D(calc_result[25]),
    .Q(result_o[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0400_ (
    .CLK(clk),
    .D(calc_result[26]),
    .Q(result_o[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0401_ (
    .CLK(clk),
    .D(calc_result[27]),
    .Q(result_o[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0402_ (
    .CLK(clk),
    .D(calc_result[28]),
    .Q(result_o[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0403_ (
    .CLK(clk),
    .D(calc_result[29]),
    .Q(result_o[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0404_ (
    .CLK(clk),
    .D(calc_result[30]),
    .Q(result_o[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0405_ (
    .CLK(clk),
    .D(calc_result[31]),
    .Q(result_o[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0406_ (
    .CLK(clk),
    .D(calc_target[0]),
    .Q(branch_target_o[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0407_ (
    .CLK(clk),
    .D(calc_target[1]),
    .Q(branch_target_o[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0408_ (
    .CLK(clk),
    .D(calc_target[2]),
    .Q(branch_target_o[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0409_ (
    .CLK(clk),
    .D(calc_target[3]),
    .Q(branch_target_o[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0410_ (
    .CLK(clk),
    .D(calc_target[4]),
    .Q(branch_target_o[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0411_ (
    .CLK(clk),
    .D(calc_target[5]),
    .Q(branch_target_o[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0412_ (
    .CLK(clk),
    .D(calc_target[6]),
    .Q(branch_target_o[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0413_ (
    .CLK(clk),
    .D(calc_target[7]),
    .Q(branch_target_o[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0414_ (
    .CLK(clk),
    .D(calc_target[8]),
    .Q(branch_target_o[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0415_ (
    .CLK(clk),
    .D(calc_target[9]),
    .Q(branch_target_o[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0416_ (
    .CLK(clk),
    .D(calc_target[10]),
    .Q(branch_target_o[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0417_ (
    .CLK(clk),
    .D(calc_target[11]),
    .Q(branch_target_o[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0418_ (
    .CLK(clk),
    .D(calc_target[12]),
    .Q(branch_target_o[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0419_ (
    .CLK(clk),
    .D(calc_target[13]),
    .Q(branch_target_o[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0420_ (
    .CLK(clk),
    .D(calc_target[14]),
    .Q(branch_target_o[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0421_ (
    .CLK(clk),
    .D(calc_target[15]),
    .Q(branch_target_o[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0422_ (
    .CLK(clk),
    .D(calc_target[16]),
    .Q(branch_target_o[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0423_ (
    .CLK(clk),
    .D(calc_target[17]),
    .Q(branch_target_o[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0424_ (
    .CLK(clk),
    .D(calc_target[18]),
    .Q(branch_target_o[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0425_ (
    .CLK(clk),
    .D(calc_target[19]),
    .Q(branch_target_o[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0426_ (
    .CLK(clk),
    .D(calc_target[20]),
    .Q(branch_target_o[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0427_ (
    .CLK(clk),
    .D(calc_target[21]),
    .Q(branch_target_o[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0428_ (
    .CLK(clk),
    .D(calc_target[22]),
    .Q(branch_target_o[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0429_ (
    .CLK(clk),
    .D(calc_target[23]),
    .Q(branch_target_o[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0430_ (
    .CLK(clk),
    .D(calc_target[24]),
    .Q(branch_target_o[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0431_ (
    .CLK(clk),
    .D(calc_target[25]),
    .Q(branch_target_o[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0432_ (
    .CLK(clk),
    .D(calc_target[26]),
    .Q(branch_target_o[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0433_ (
    .CLK(clk),
    .D(calc_target[27]),
    .Q(branch_target_o[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0434_ (
    .CLK(clk),
    .D(calc_target[28]),
    .Q(branch_target_o[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0435_ (
    .CLK(clk),
    .D(calc_target[29]),
    .Q(branch_target_o[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0436_ (
    .CLK(clk),
    .D(calc_target[30]),
    .Q(branch_target_o[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0437_ (
    .CLK(clk),
    .D(calc_target[31]),
    .Q(branch_target_o[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0438_ (
    .CLK(clk),
    .D(calc_taken),
    .Q(branch_taken_o),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0439_ (
    .CLK(clk),
    .D(rob_id_i[0]),
    .Q(rob_id_o[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0440_ (
    .CLK(clk),
    .D(rob_id_i[1]),
    .Q(rob_id_o[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0441_ (
    .CLK(clk),
    .D(rob_id_i[2]),
    .Q(rob_id_o[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0442_ (
    .CLK(clk),
    .D(rob_id_i[3]),
    .Q(rob_id_o[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0443_ (
    .CLK(clk),
    .D(rob_id_i[4]),
    .Q(rob_id_o[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0444_ (
    .CLK(clk),
    .D(rob_id_i[5]),
    .Q(rob_id_o[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0445_ (
    .CLK(clk),
    .D(phys_dest_i[0]),
    .Q(phys_dest_o[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0446_ (
    .CLK(clk),
    .D(phys_dest_i[1]),
    .Q(phys_dest_o[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0447_ (
    .CLK(clk),
    .D(phys_dest_i[2]),
    .Q(phys_dest_o[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0448_ (
    .CLK(clk),
    .D(phys_dest_i[3]),
    .Q(phys_dest_o[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0449_ (
    .CLK(clk),
    .D(phys_dest_i[4]),
    .Q(phys_dest_o[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0450_ (
    .CLK(clk),
    .D(phys_dest_i[5]),
    .Q(phys_dest_o[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0451_ (
    .CLK(clk),
    .D(phys_dest_i[6]),
    .Q(phys_dest_o[6]),
    .RESET_B(rst_n)
  );
  assign _0000_ = ~op_i[1];
  assign _0001_ = ~op_i[0];
  assign _0002_ = ~op_i[2];
  assign _0003_ = ~op_i[3];
  assign _0004_[0] = _0071_[17] | _0071_[49];
  assign _0073_[17] = _0004_[0] | _0071_[81];
  assign _0005_[0] = _0071_[16] | _0071_[48];
  assign _0073_[16] = _0005_[0] | _0071_[80];
  assign _0006_[0] = _0071_[15] | _0071_[47];
  assign _0073_[15] = _0006_[0] | _0071_[79];
  assign _0007_[0] = _0071_[14] | _0071_[46];
  assign _0073_[14] = _0007_[0] | _0071_[78];
  assign _0008_[0] = _0071_[13] | _0071_[45];
  assign _0073_[13] = _0008_[0] | _0071_[77];
  assign _0009_[0] = _0071_[12] | _0071_[44];
  assign _0073_[12] = _0009_[0] | _0071_[76];
  assign _0010_[0] = _0071_[11] | _0071_[43];
  assign _0073_[11] = _0010_[0] | _0071_[75];
  assign _0011_[0] = _0071_[10] | _0071_[42];
  assign _0073_[10] = _0011_[0] | _0071_[74];
  assign _0012_[0] = _0071_[9] | _0071_[41];
  assign _0073_[9] = _0012_[0] | _0071_[73];
  assign _0013_[0] = _0071_[8] | _0071_[40];
  assign _0073_[8] = _0013_[0] | _0071_[72];
  assign _0014_[0] = _0071_[7] | _0071_[39];
  assign _0073_[7] = _0014_[0] | _0071_[71];
  assign _0015_[0] = _0071_[6] | _0071_[38];
  assign _0073_[6] = _0015_[0] | _0071_[70];
  assign _0016_[0] = _0071_[5] | _0071_[37];
  assign _0073_[5] = _0016_[0] | _0071_[69];
  assign _0017_[0] = _0071_[4] | _0071_[36];
  assign _0073_[4] = _0017_[0] | _0071_[68];
  assign _0018_[0] = _0071_[3] | _0071_[35];
  assign _0073_[3] = _0018_[0] | _0071_[67];
  assign _0019_[0] = _0071_[2] | _0071_[34];
  assign _0073_[2] = _0019_[0] | _0071_[66];
  assign _0020_[0] = _0071_[1] | _0071_[33];
  assign _0073_[1] = _0020_[0] | _0071_[65];
  assign _0021_[0] = _0071_[0] | _0071_[32];
  assign _0021_[1] = _0071_[64] | _0071_[96];
  assign _0022_[0] = _0021_[0] | _0021_[1];
  assign _0022_[1] = _0021_[2] | _0021_[3];
  assign _0023_ = _0022_[0] | _0022_[1];
  assign _0073_[0] = _0023_ | _0071_[256];
  assign _0024_[0] = _0072_[0] | _0072_[1];
  assign _0025_[0] = _0024_[0] | _0024_[1];
  assign _0025_[1] = _0024_[2] | _0024_[3];
  assign _0026_ = _0025_[0] | _0025_[1];
  assign _0096_ = _0026_ | _0072_[8];
  assign _0078_[31] = _0076_[31] | _0076_[63];
  assign _0078_[30] = _0076_[30] | _0076_[62];
  assign _0078_[29] = _0076_[29] | _0076_[61];
  assign _0078_[28] = _0076_[28] | _0076_[60];
  assign _0078_[27] = _0076_[27] | _0076_[59];
  assign _0078_[26] = _0076_[26] | _0076_[58];
  assign _0078_[25] = _0076_[25] | _0076_[57];
  assign _0078_[24] = _0076_[24] | _0076_[56];
  assign _0078_[23] = _0076_[23] | _0076_[55];
  assign _0078_[22] = _0076_[22] | _0076_[54];
  assign _0078_[21] = _0076_[21] | _0076_[53];
  assign _0078_[20] = _0076_[20] | _0076_[52];
  assign _0078_[19] = _0076_[19] | _0076_[51];
  assign _0078_[18] = _0076_[18] | _0076_[50];
  assign _0078_[17] = _0076_[17] | _0076_[49];
  assign _0078_[16] = _0076_[16] | _0076_[48];
  assign _0078_[15] = _0076_[15] | _0076_[47];
  assign _0078_[14] = _0076_[14] | _0076_[46];
  assign _0078_[13] = _0076_[13] | _0076_[45];
  assign _0078_[12] = _0076_[12] | _0076_[44];
  assign _0078_[11] = _0076_[11] | _0076_[43];
  assign _0078_[10] = _0076_[10] | _0076_[42];
  assign _0078_[9] = _0076_[9] | _0076_[41];
  assign _0078_[8] = _0076_[8] | _0076_[40];
  assign _0078_[7] = _0076_[7] | _0076_[39];
  assign _0078_[6] = _0076_[6] | _0076_[38];
  assign _0078_[5] = _0076_[5] | _0076_[37];
  assign _0078_[4] = _0076_[4] | _0076_[36];
  assign _0078_[3] = _0076_[3] | _0076_[35];
  assign _0078_[2] = _0076_[2] | _0076_[34];
  assign _0078_[1] = _0076_[1] | _0076_[33];
  assign _0097_ = _0077_[0] | _0077_[1];
  assign _0027_[0] = _0072_[2] | _0071_[96];
  assign _0021_[2] = _0071_[128] | _0071_[160];
  assign _0021_[3] = _0071_[192] | _0071_[224];
  assign _0028_[0] = _0027_[0] | _0021_[2];
  assign _0028_[1] = _0021_[3] | _0071_[256];
  assign _0079_ = _0028_[0] | _0028_[1];
  assign _0024_[1] = _0072_[2] | _0072_[3];
  assign _0024_[2] = _0072_[4] | _0072_[5];
  assign _0024_[3] = _0072_[6] | _0072_[7];
  assign _0029_[0] = _0024_[1] | _0024_[2];
  assign _0029_[1] = _0024_[3] | _0072_[8];
  assign _0098_ = _0029_[0] | _0029_[1];
  assign _0033_[1] = _0032_[2] | _0032_[3];
  assign _0030_[0] = _0060_[0] | _0060_[1];
  assign _0030_[1] = _0060_[2] | _0060_[3];
  assign _0030_[2] = _0060_[4] | _0060_[5];
  assign _0030_[3] = _0060_[6] | _0060_[7];
  assign _0030_[4] = _0060_[8] | _0060_[9];
  assign _0030_[5] = _0060_[10] | _0060_[11];
  assign _0030_[6] = _0060_[12] | _0060_[13];
  assign _0030_[7] = _0060_[14] | _0060_[15];
  assign _0030_[8] = _0060_[16] | _0060_[17];
  assign _0030_[9] = _0060_[18] | _0060_[19];
  assign _0030_[10] = _0060_[20] | _0060_[21];
  assign _0030_[11] = _0060_[22] | _0060_[23];
  assign _0030_[12] = _0060_[24] | _0060_[25];
  assign _0030_[13] = _0060_[26] | _0060_[27];
  assign _0030_[14] = _0060_[28] | _0060_[29];
  assign _0030_[15] = _0060_[30] | _0060_[31];
  assign _0031_[0] = _0030_[0] | _0030_[1];
  assign _0031_[1] = _0030_[2] | _0030_[3];
  assign _0031_[2] = _0030_[4] | _0030_[5];
  assign _0031_[3] = _0030_[6] | _0030_[7];
  assign _0031_[4] = _0030_[8] | _0030_[9];
  assign _0031_[5] = _0030_[10] | _0030_[11];
  assign _0031_[6] = _0030_[12] | _0030_[13];
  assign _0031_[7] = _0030_[14] | _0030_[15];
  assign _0032_[0] = _0031_[0] | _0031_[1];
  assign _0032_[1] = _0031_[2] | _0031_[3];
  assign _0032_[2] = _0031_[4] | _0031_[5];
  assign _0032_[3] = _0031_[6] | _0031_[7];
  assign _0033_[0] = _0032_[0] | _0032_[1];
  assign _0070_[224] = _0033_[0] | _0033_[1];
  assign _0072_[2] = _0077_[0] | _0074_;
  assign _0034_[0] = _0074_ | _0072_[3];
  assign _0035_[0] = _0034_[0] | _0024_[2];
  assign _0077_[1] = _0035_[0] | _0029_[1];
  assign _0061_ = _0036_[0] | _0036_[1];
  assign _0036_[1] = op_i[2] | _0003_;
  assign _0062_ = _0037_[0] | _0036_[1];
  assign _0063_ = _0038_[0] | _0038_[1];
  assign _0064_ = _0039_[0] | _0038_[1];
  assign _0065_ = _0036_[0] | _0038_[1];
  assign _0038_[1] = _0002_ | op_i[3];
  assign _0066_ = _0037_[0] | _0038_[1];
  assign _0038_[0] = _0001_ | _0000_;
  assign _0067_ = _0038_[0] | _0040_[1];
  assign _0039_[0] = op_i[0] | _0000_;
  assign _0068_ = _0039_[0] | _0040_[1];
  assign _0036_[0] = _0001_ | op_i[1];
  assign _0069_ = _0036_[0] | _0040_[1];
  assign _0041_[0] = _0089_[0] & _0089_[1];
  assign _0042_[0] = _0041_[0] & _0041_[1];
  assign _0043_[0] = _0042_[0] & _0042_[1];
  assign _0044_[0] = _0043_[0] & _0043_[1];
  assign _0092_ = _0044_[0] & _0044_[1];
  assign _0045_[0] = _0071_[31] | _0071_[63];
  assign _0073_[31] = _0045_[0] | _0071_[95];
  assign _0046_[0] = _0071_[30] | _0071_[62];
  assign _0073_[30] = _0046_[0] | _0071_[94];
  assign _0047_[0] = _0071_[29] | _0071_[61];
  assign _0073_[29] = _0047_[0] | _0071_[93];
  assign _0048_[0] = _0071_[28] | _0071_[60];
  assign _0073_[28] = _0048_[0] | _0071_[92];
  assign _0049_[0] = _0071_[27] | _0071_[59];
  assign _0073_[27] = _0049_[0] | _0071_[91];
  assign _0050_[0] = _0071_[26] | _0071_[58];
  assign _0073_[26] = _0050_[0] | _0071_[90];
  assign _0051_[0] = _0071_[25] | _0071_[57];
  assign _0073_[25] = _0051_[0] | _0071_[89];
  assign _0052_[0] = _0071_[24] | _0071_[56];
  assign _0073_[24] = _0052_[0] | _0071_[88];
  assign _0053_[0] = _0071_[23] | _0071_[55];
  assign _0073_[23] = _0053_[0] | _0071_[87];
  assign _0054_[0] = _0071_[22] | _0071_[54];
  assign _0073_[22] = _0054_[0] | _0071_[86];
  assign _0055_[0] = _0071_[21] | _0071_[53];
  assign _0073_[21] = _0055_[0] | _0071_[85];
  assign _0056_[0] = _0071_[20] | _0071_[52];
  assign _0073_[20] = _0056_[0] | _0071_[84];
  assign _0057_[0] = _0071_[19] | _0071_[51];
  assign _0073_[19] = _0057_[0] | _0071_[83];
  assign _0058_[0] = _0071_[18] | _0071_[50];
  assign _0073_[18] = _0058_[0] | _0071_[82];
  assign _0037_[0] = op_i[0] | op_i[1];
  assign _0040_[1] = op_i[2] | op_i[3];
  assign _0059_ = _0037_[0] | _0040_[1];
  assign _0070_[256] = ~_0070_[224];
  assign _0072_[0] = ~_0061_;
  assign _0072_[1] = ~_0062_;
  assign _0077_[0] = ~_0063_;
  assign _0074_ = ~_0064_;
  assign _0072_[3] = ~_0065_;
  assign _0072_[4] = ~_0066_;
  assign _0072_[5] = ~_0067_;
  assign _0072_[6] = ~_0068_;
  assign _0072_[7] = ~_0069_;
  assign _0072_[8] = ~_0059_;
  assign calc_result[0] = _0096_ ? _0073_[0] : 1'h0;
  assign calc_result[1] = _0096_ ? _0073_[1] : 1'h0;
  assign calc_result[2] = _0096_ ? _0073_[2] : 1'h0;
  assign calc_result[3] = _0096_ ? _0073_[3] : 1'h0;
  assign calc_result[4] = _0096_ ? _0073_[4] : 1'h0;
  assign calc_result[5] = _0096_ ? _0073_[5] : 1'h0;
  assign calc_result[6] = _0096_ ? _0073_[6] : 1'h0;
  assign calc_result[7] = _0096_ ? _0073_[7] : 1'h0;
  assign calc_result[8] = _0096_ ? _0073_[8] : 1'h0;
  assign calc_result[9] = _0096_ ? _0073_[9] : 1'h0;
  assign calc_result[10] = _0096_ ? _0073_[10] : 1'h0;
  assign calc_result[11] = _0096_ ? _0073_[11] : 1'h0;
  assign calc_result[12] = _0096_ ? _0073_[12] : 1'h0;
  assign calc_result[13] = _0096_ ? _0073_[13] : 1'h0;
  assign calc_result[14] = _0096_ ? _0073_[14] : 1'h0;
  assign calc_result[15] = _0096_ ? _0073_[15] : 1'h0;
  assign calc_result[16] = _0096_ ? _0073_[16] : 1'h0;
  assign calc_result[17] = _0096_ ? _0073_[17] : 1'h0;
  assign calc_result[18] = _0096_ ? _0073_[18] : 1'h0;
  assign calc_result[19] = _0096_ ? _0073_[19] : 1'h0;
  assign calc_result[20] = _0096_ ? _0073_[20] : 1'h0;
  assign calc_result[21] = _0096_ ? _0073_[21] : 1'h0;
  assign calc_result[22] = _0096_ ? _0073_[22] : 1'h0;
  assign calc_result[23] = _0096_ ? _0073_[23] : 1'h0;
  assign calc_result[24] = _0096_ ? _0073_[24] : 1'h0;
  assign calc_result[25] = _0096_ ? _0073_[25] : 1'h0;
  assign calc_result[26] = _0096_ ? _0073_[26] : 1'h0;
  assign calc_result[27] = _0096_ ? _0073_[27] : 1'h0;
  assign calc_result[28] = _0096_ ? _0073_[28] : 1'h0;
  assign calc_result[29] = _0096_ ? _0073_[29] : 1'h0;
  assign calc_result[30] = _0096_ ? _0073_[30] : 1'h0;
  assign calc_result[31] = _0096_ ? _0073_[31] : 1'h0;
  assign calc_target[0] = _0097_ ? _0076_[32] : 1'h0;
  assign calc_target[1] = _0097_ ? _0078_[1] : 1'h0;
  assign calc_target[2] = _0097_ ? _0078_[2] : 1'h0;
  assign calc_target[3] = _0097_ ? _0078_[3] : 1'h0;
  assign calc_target[4] = _0097_ ? _0078_[4] : 1'h0;
  assign calc_target[5] = _0097_ ? _0078_[5] : 1'h0;
  assign calc_target[6] = _0097_ ? _0078_[6] : 1'h0;
  assign calc_target[7] = _0097_ ? _0078_[7] : 1'h0;
  assign calc_target[8] = _0097_ ? _0078_[8] : 1'h0;
  assign calc_target[9] = _0097_ ? _0078_[9] : 1'h0;
  assign calc_target[10] = _0097_ ? _0078_[10] : 1'h0;
  assign calc_target[11] = _0097_ ? _0078_[11] : 1'h0;
  assign calc_target[12] = _0097_ ? _0078_[12] : 1'h0;
  assign calc_target[13] = _0097_ ? _0078_[13] : 1'h0;
  assign calc_target[14] = _0097_ ? _0078_[14] : 1'h0;
  assign calc_target[15] = _0097_ ? _0078_[15] : 1'h0;
  assign calc_target[16] = _0097_ ? _0078_[16] : 1'h0;
  assign calc_target[17] = _0097_ ? _0078_[17] : 1'h0;
  assign calc_target[18] = _0097_ ? _0078_[18] : 1'h0;
  assign calc_target[19] = _0097_ ? _0078_[19] : 1'h0;
  assign calc_target[20] = _0097_ ? _0078_[20] : 1'h0;
  assign calc_target[21] = _0097_ ? _0078_[21] : 1'h0;
  assign calc_target[22] = _0097_ ? _0078_[22] : 1'h0;
  assign calc_target[23] = _0097_ ? _0078_[23] : 1'h0;
  assign calc_target[24] = _0097_ ? _0078_[24] : 1'h0;
  assign calc_target[25] = _0097_ ? _0078_[25] : 1'h0;
  assign calc_target[26] = _0097_ ? _0078_[26] : 1'h0;
  assign calc_target[27] = _0097_ ? _0078_[27] : 1'h0;
  assign calc_target[28] = _0097_ ? _0078_[28] : 1'h0;
  assign calc_target[29] = _0097_ ? _0078_[29] : 1'h0;
  assign calc_target[30] = _0097_ ? _0078_[30] : 1'h0;
  assign calc_target[31] = _0097_ ? _0078_[31] : 1'h0;
  assign calc_taken = _0098_ ? _0079_ : 1'h0;
  assign _0087_[0] = ~operand_a_i[0];
  assign _0087_[1] = ~operand_a_i[1];
  assign _0087_[2] = ~operand_a_i[2];
  assign _0087_[3] = ~operand_a_i[3];
  assign _0087_[4] = ~operand_a_i[4];
  assign _0087_[5] = ~operand_a_i[5];
  assign _0087_[6] = ~operand_a_i[6];
  assign _0087_[7] = ~operand_a_i[7];
  assign _0087_[8] = ~operand_a_i[8];
  assign _0087_[9] = ~operand_a_i[9];
  assign _0087_[10] = ~operand_a_i[10];
  assign _0087_[11] = ~operand_a_i[11];
  assign _0087_[12] = ~operand_a_i[12];
  assign _0087_[13] = ~operand_a_i[13];
  assign _0087_[14] = ~operand_a_i[14];
  assign _0087_[15] = ~operand_a_i[15];
  assign _0087_[16] = ~operand_a_i[16];
  assign _0087_[17] = ~operand_a_i[17];
  assign _0087_[18] = ~operand_a_i[18];
  assign _0087_[19] = ~operand_a_i[19];
  assign _0087_[20] = ~operand_a_i[20];
  assign _0087_[21] = ~operand_a_i[21];
  assign _0087_[22] = ~operand_a_i[22];
  assign _0087_[23] = ~operand_a_i[23];
  assign _0087_[24] = ~operand_a_i[24];
  assign _0087_[25] = ~operand_a_i[25];
  assign _0087_[26] = ~operand_a_i[26];
  assign _0087_[27] = ~operand_a_i[27];
  assign _0087_[28] = ~operand_a_i[28];
  assign _0087_[29] = ~operand_a_i[29];
  assign _0087_[30] = ~operand_a_i[30];
  assign _0087_[31] = ~operand_a_i[31];
  assign _0070_[66] = ~pc_i[2];
  assign _0070_[192] = ~_0070_[160];
  assign _0070_[128] = ~_0070_[96];
  assign _0095_ = ~_0088_[31];
  assign _0071_[256] = _0070_[256] & _0072_[8];
  assign _0071_[224] = _0070_[224] & _0072_[7];
  assign _0071_[192] = _0070_[192] & _0072_[6];
  assign _0071_[160] = _0070_[160] & _0072_[5];
  assign _0071_[128] = _0070_[128] & _0072_[4];
  assign _0071_[96] = _0070_[96] & _0072_[3];
  assign _0071_[64] = pc_i[0] & _0072_[2];
  assign _0071_[65] = pc_i[1] & _0072_[2];
  assign _0071_[66] = _0070_[66] & _0072_[2];
  assign _0071_[67] = _0070_[67] & _0072_[2];
  assign _0071_[68] = _0070_[68] & _0072_[2];
  assign _0071_[69] = _0070_[69] & _0072_[2];
  assign _0071_[70] = _0070_[70] & _0072_[2];
  assign _0071_[71] = _0070_[71] & _0072_[2];
  assign _0071_[72] = _0070_[72] & _0072_[2];
  assign _0071_[73] = _0070_[73] & _0072_[2];
  assign _0071_[74] = _0070_[74] & _0072_[2];
  assign _0071_[75] = _0070_[75] & _0072_[2];
  assign _0071_[76] = _0070_[76] & _0072_[2];
  assign _0071_[77] = _0070_[77] & _0072_[2];
  assign _0071_[78] = _0070_[78] & _0072_[2];
  assign _0071_[79] = _0070_[79] & _0072_[2];
  assign _0071_[80] = _0070_[80] & _0072_[2];
  assign _0071_[81] = _0070_[81] & _0072_[2];
  assign _0071_[82] = _0070_[82] & _0072_[2];
  assign _0071_[83] = _0070_[83] & _0072_[2];
  assign _0071_[84] = _0070_[84] & _0072_[2];
  assign _0071_[85] = _0070_[85] & _0072_[2];
  assign _0071_[86] = _0070_[86] & _0072_[2];
  assign _0071_[87] = _0070_[87] & _0072_[2];
  assign _0071_[88] = _0070_[88] & _0072_[2];
  assign _0071_[89] = _0070_[89] & _0072_[2];
  assign _0071_[90] = _0070_[90] & _0072_[2];
  assign _0071_[91] = _0070_[91] & _0072_[2];
  assign _0071_[92] = _0070_[92] & _0072_[2];
  assign _0071_[93] = _0070_[93] & _0072_[2];
  assign _0071_[94] = _0070_[94] & _0072_[2];
  assign _0071_[95] = _0070_[95] & _0072_[2];
  assign _0071_[32] = imm_i[0] & _0072_[1];
  assign _0071_[33] = imm_i[1] & _0072_[1];
  assign _0071_[34] = imm_i[2] & _0072_[1];
  assign _0071_[35] = imm_i[3] & _0072_[1];
  assign _0071_[36] = imm_i[4] & _0072_[1];
  assign _0071_[37] = imm_i[5] & _0072_[1];
  assign _0071_[38] = imm_i[6] & _0072_[1];
  assign _0071_[39] = imm_i[7] & _0072_[1];
  assign _0071_[40] = imm_i[8] & _0072_[1];
  assign _0071_[41] = imm_i[9] & _0072_[1];
  assign _0071_[42] = imm_i[10] & _0072_[1];
  assign _0071_[43] = imm_i[11] & _0072_[1];
  assign _0071_[44] = imm_i[12] & _0072_[1];
  assign _0071_[45] = imm_i[13] & _0072_[1];
  assign _0071_[46] = imm_i[14] & _0072_[1];
  assign _0071_[47] = imm_i[15] & _0072_[1];
  assign _0071_[48] = imm_i[16] & _0072_[1];
  assign _0071_[49] = imm_i[17] & _0072_[1];
  assign _0071_[50] = imm_i[18] & _0072_[1];
  assign _0071_[51] = imm_i[19] & _0072_[1];
  assign _0071_[52] = imm_i[20] & _0072_[1];
  assign _0071_[53] = imm_i[21] & _0072_[1];
  assign _0071_[54] = imm_i[22] & _0072_[1];
  assign _0071_[55] = imm_i[23] & _0072_[1];
  assign _0071_[56] = imm_i[24] & _0072_[1];
  assign _0071_[57] = imm_i[25] & _0072_[1];
  assign _0071_[58] = imm_i[26] & _0072_[1];
  assign _0071_[59] = imm_i[27] & _0072_[1];
  assign _0071_[60] = imm_i[28] & _0072_[1];
  assign _0071_[61] = imm_i[29] & _0072_[1];
  assign _0071_[62] = imm_i[30] & _0072_[1];
  assign _0071_[63] = imm_i[31] & _0072_[1];
  assign _0071_[0] = _0070_[0] & _0072_[0];
  assign _0071_[1] = _0070_[1] & _0072_[0];
  assign _0071_[2] = _0070_[2] & _0072_[0];
  assign _0071_[3] = _0070_[3] & _0072_[0];
  assign _0071_[4] = _0070_[4] & _0072_[0];
  assign _0071_[5] = _0070_[5] & _0072_[0];
  assign _0071_[6] = _0070_[6] & _0072_[0];
  assign _0071_[7] = _0070_[7] & _0072_[0];
  assign _0071_[8] = _0070_[8] & _0072_[0];
  assign _0071_[9] = _0070_[9] & _0072_[0];
  assign _0071_[10] = _0070_[10] & _0072_[0];
  assign _0071_[11] = _0070_[11] & _0072_[0];
  assign _0071_[12] = _0070_[12] & _0072_[0];
  assign _0071_[13] = _0070_[13] & _0072_[0];
  assign _0071_[14] = _0070_[14] & _0072_[0];
  assign _0071_[15] = _0070_[15] & _0072_[0];
  assign _0071_[16] = _0070_[16] & _0072_[0];
  assign _0071_[17] = _0070_[17] & _0072_[0];
  assign _0071_[18] = _0070_[18] & _0072_[0];
  assign _0071_[19] = _0070_[19] & _0072_[0];
  assign _0071_[20] = _0070_[20] & _0072_[0];
  assign _0071_[21] = _0070_[21] & _0072_[0];
  assign _0071_[22] = _0070_[22] & _0072_[0];
  assign _0071_[23] = _0070_[23] & _0072_[0];
  assign _0071_[24] = _0070_[24] & _0072_[0];
  assign _0071_[25] = _0070_[25] & _0072_[0];
  assign _0071_[26] = _0070_[26] & _0072_[0];
  assign _0071_[27] = _0070_[27] & _0072_[0];
  assign _0071_[28] = _0070_[28] & _0072_[0];
  assign _0071_[29] = _0070_[29] & _0072_[0];
  assign _0071_[30] = _0070_[30] & _0072_[0];
  assign _0071_[31] = _0070_[31] & _0072_[0];
  assign _0076_[32] = _0070_[0] & _0077_[1];
  assign _0076_[33] = _0070_[1] & _0077_[1];
  assign _0076_[34] = _0070_[2] & _0077_[1];
  assign _0076_[35] = _0070_[3] & _0077_[1];
  assign _0076_[36] = _0070_[4] & _0077_[1];
  assign _0076_[37] = _0070_[5] & _0077_[1];
  assign _0076_[38] = _0070_[6] & _0077_[1];
  assign _0076_[39] = _0070_[7] & _0077_[1];
  assign _0076_[40] = _0070_[8] & _0077_[1];
  assign _0076_[41] = _0070_[9] & _0077_[1];
  assign _0076_[42] = _0070_[10] & _0077_[1];
  assign _0076_[43] = _0070_[11] & _0077_[1];
  assign _0076_[44] = _0070_[12] & _0077_[1];
  assign _0076_[45] = _0070_[13] & _0077_[1];
  assign _0076_[46] = _0070_[14] & _0077_[1];
  assign _0076_[47] = _0070_[15] & _0077_[1];
  assign _0076_[48] = _0070_[16] & _0077_[1];
  assign _0076_[49] = _0070_[17] & _0077_[1];
  assign _0076_[50] = _0070_[18] & _0077_[1];
  assign _0076_[51] = _0070_[19] & _0077_[1];
  assign _0076_[52] = _0070_[20] & _0077_[1];
  assign _0076_[53] = _0070_[21] & _0077_[1];
  assign _0076_[54] = _0070_[22] & _0077_[1];
  assign _0076_[55] = _0070_[23] & _0077_[1];
  assign _0076_[56] = _0070_[24] & _0077_[1];
  assign _0076_[57] = _0070_[25] & _0077_[1];
  assign _0076_[58] = _0070_[26] & _0077_[1];
  assign _0076_[59] = _0070_[27] & _0077_[1];
  assign _0076_[60] = _0070_[28] & _0077_[1];
  assign _0076_[61] = _0070_[29] & _0077_[1];
  assign _0076_[62] = _0070_[30] & _0077_[1];
  assign _0076_[63] = _0070_[31] & _0077_[1];
  assign _0076_[1] = _0075_[1] & _0077_[0];
  assign _0076_[2] = _0075_[2] & _0077_[0];
  assign _0076_[3] = _0075_[3] & _0077_[0];
  assign _0076_[4] = _0075_[4] & _0077_[0];
  assign _0076_[5] = _0075_[5] & _0077_[0];
  assign _0076_[6] = _0075_[6] & _0077_[0];
  assign _0076_[7] = _0075_[7] & _0077_[0];
  assign _0076_[8] = _0075_[8] & _0077_[0];
  assign _0076_[9] = _0075_[9] & _0077_[0];
  assign _0076_[10] = _0075_[10] & _0077_[0];
  assign _0076_[11] = _0075_[11] & _0077_[0];
  assign _0076_[12] = _0075_[12] & _0077_[0];
  assign _0076_[13] = _0075_[13] & _0077_[0];
  assign _0076_[14] = _0075_[14] & _0077_[0];
  assign _0076_[15] = _0075_[15] & _0077_[0];
  assign _0076_[16] = _0075_[16] & _0077_[0];
  assign _0076_[17] = _0075_[17] & _0077_[0];
  assign _0076_[18] = _0075_[18] & _0077_[0];
  assign _0076_[19] = _0075_[19] & _0077_[0];
  assign _0076_[20] = _0075_[20] & _0077_[0];
  assign _0076_[21] = _0075_[21] & _0077_[0];
  assign _0076_[22] = _0075_[22] & _0077_[0];
  assign _0076_[23] = _0075_[23] & _0077_[0];
  assign _0076_[24] = _0075_[24] & _0077_[0];
  assign _0076_[25] = _0075_[25] & _0077_[0];
  assign _0076_[26] = _0075_[26] & _0077_[0];
  assign _0076_[27] = _0075_[27] & _0077_[0];
  assign _0076_[28] = _0075_[28] & _0077_[0];
  assign _0076_[29] = _0075_[29] & _0077_[0];
  assign _0076_[30] = _0075_[30] & _0077_[0];
  assign _0076_[31] = _0075_[31] & _0077_[0];
  assign _0090_[31] = _0089_[31] ^ _0088_[30];
  assign _0060_[0] = operand_a_i[0] ^ operand_b_i[0];
  assign _0060_[1] = operand_a_i[1] ^ operand_b_i[1];
  assign _0060_[2] = operand_a_i[2] ^ operand_b_i[2];
  assign _0060_[3] = operand_a_i[3] ^ operand_b_i[3];
  assign _0060_[4] = operand_a_i[4] ^ operand_b_i[4];
  assign _0060_[5] = operand_a_i[5] ^ operand_b_i[5];
  assign _0060_[6] = operand_a_i[6] ^ operand_b_i[6];
  assign _0060_[7] = operand_a_i[7] ^ operand_b_i[7];
  assign _0060_[8] = operand_a_i[8] ^ operand_b_i[8];
  assign _0060_[9] = operand_a_i[9] ^ operand_b_i[9];
  assign _0060_[10] = operand_a_i[10] ^ operand_b_i[10];
  assign _0060_[11] = operand_a_i[11] ^ operand_b_i[11];
  assign _0060_[12] = operand_a_i[12] ^ operand_b_i[12];
  assign _0060_[13] = operand_a_i[13] ^ operand_b_i[13];
  assign _0060_[14] = operand_a_i[14] ^ operand_b_i[14];
  assign _0060_[15] = operand_a_i[15] ^ operand_b_i[15];
  assign _0060_[16] = operand_a_i[16] ^ operand_b_i[16];
  assign _0060_[17] = operand_a_i[17] ^ operand_b_i[17];
  assign _0060_[18] = operand_a_i[18] ^ operand_b_i[18];
  assign _0089_[0] = operand_b_i[0] ^ _0087_[0];
  assign _0089_[1] = operand_b_i[1] ^ _0087_[1];
  assign _0089_[2] = operand_b_i[2] ^ _0087_[2];
  assign _0089_[3] = operand_b_i[3] ^ _0087_[3];
  assign _0060_[19] = operand_a_i[19] ^ operand_b_i[19];
  assign _0089_[4] = operand_b_i[4] ^ _0087_[4];
  assign _0089_[5] = operand_b_i[5] ^ _0087_[5];
  assign _0089_[6] = operand_b_i[6] ^ _0087_[6];
  assign _0089_[7] = operand_b_i[7] ^ _0087_[7];
  assign _0089_[8] = operand_b_i[8] ^ _0087_[8];
  assign _0089_[9] = operand_b_i[9] ^ _0087_[9];
  assign _0089_[10] = operand_b_i[10] ^ _0087_[10];
  assign _0089_[11] = operand_b_i[11] ^ _0087_[11];
  assign _0089_[12] = operand_b_i[12] ^ _0087_[12];
  assign _0089_[13] = operand_b_i[13] ^ _0087_[13];
  assign _0060_[20] = operand_a_i[20] ^ operand_b_i[20];
  assign _0089_[14] = operand_b_i[14] ^ _0087_[14];
  assign _0089_[15] = operand_b_i[15] ^ _0087_[15];
  assign _0089_[16] = operand_b_i[16] ^ _0087_[16];
  assign _0089_[17] = operand_b_i[17] ^ _0087_[17];
  assign _0089_[18] = operand_b_i[18] ^ _0087_[18];
  assign _0089_[19] = operand_b_i[19] ^ _0087_[19];
  assign _0089_[20] = operand_b_i[20] ^ _0087_[20];
  assign _0089_[21] = operand_b_i[21] ^ _0087_[21];
  assign _0089_[22] = operand_b_i[22] ^ _0087_[22];
  assign _0089_[23] = operand_b_i[23] ^ _0087_[23];
  assign _0060_[21] = operand_a_i[21] ^ operand_b_i[21];
  assign _0089_[24] = operand_b_i[24] ^ _0087_[24];
  assign _0089_[25] = operand_b_i[25] ^ _0087_[25];
  assign _0089_[26] = operand_b_i[26] ^ _0087_[26];
  assign _0089_[27] = operand_b_i[27] ^ _0087_[27];
  assign _0089_[28] = operand_b_i[28] ^ _0087_[28];
  assign _0089_[29] = operand_b_i[29] ^ _0087_[29];
  assign _0089_[30] = operand_b_i[30] ^ _0087_[30];
  assign _0089_[31] = operand_b_i[31] ^ _0087_[31];
  assign _0091_[0] = operand_b_i[0] & _0087_[0];
  assign _0091_[1] = operand_b_i[1] & _0087_[1];
  assign _0060_[22] = operand_a_i[22] ^ operand_b_i[22];
  assign _0091_[2] = operand_b_i[2] & _0087_[2];
  assign _0091_[3] = operand_b_i[3] & _0087_[3];
  assign _0091_[4] = operand_b_i[4] & _0087_[4];
  assign _0091_[5] = operand_b_i[5] & _0087_[5];
  assign _0091_[6] = operand_b_i[6] & _0087_[6];
  assign _0091_[7] = operand_b_i[7] & _0087_[7];
  assign _0091_[8] = operand_b_i[8] & _0087_[8];
  assign _0091_[9] = operand_b_i[9] & _0087_[9];
  assign _0091_[10] = operand_b_i[10] & _0087_[10];
  assign _0091_[11] = operand_b_i[11] & _0087_[11];
  assign _0060_[23] = operand_a_i[23] ^ operand_b_i[23];
  assign _0091_[12] = operand_b_i[12] & _0087_[12];
  assign _0091_[13] = operand_b_i[13] & _0087_[13];
  assign _0091_[14] = operand_b_i[14] & _0087_[14];
  assign _0091_[15] = operand_b_i[15] & _0087_[15];
  assign _0091_[16] = operand_b_i[16] & _0087_[16];
  assign _0091_[17] = operand_b_i[17] & _0087_[17];
  assign _0091_[18] = operand_b_i[18] & _0087_[18];
  assign _0091_[19] = operand_b_i[19] & _0087_[19];
  assign _0091_[20] = operand_b_i[20] & _0087_[20];
  assign _0091_[21] = operand_b_i[21] & _0087_[21];
  assign _0060_[24] = operand_a_i[24] ^ operand_b_i[24];
  assign _0091_[22] = operand_b_i[22] & _0087_[22];
  assign _0091_[23] = operand_b_i[23] & _0087_[23];
  assign _0091_[24] = operand_b_i[24] & _0087_[24];
  assign _0091_[25] = operand_b_i[25] & _0087_[25];
  assign _0091_[26] = operand_b_i[26] & _0087_[26];
  assign _0091_[27] = operand_b_i[27] & _0087_[27];
  assign _0091_[28] = operand_b_i[28] & _0087_[28];
  assign _0091_[29] = operand_b_i[29] & _0087_[29];
  assign _0091_[30] = operand_b_i[30] & _0087_[30];
  assign _0091_[31] = operand_b_i[31] & _0087_[31];
  assign _0060_[25] = operand_a_i[25] ^ operand_b_i[25];
  assign _0060_[26] = operand_a_i[26] ^ operand_b_i[26];
  assign _0060_[27] = operand_a_i[27] ^ operand_b_i[27];
  assign _0060_[28] = operand_a_i[28] ^ operand_b_i[28];
  assign _0060_[29] = operand_a_i[29] ^ operand_b_i[29];
  assign _0060_[30] = operand_a_i[30] ^ operand_b_i[30];
  assign _0060_[31] = operand_a_i[31] ^ operand_b_i[31];
  assign _0075_[1] = _0081_[1] ^ _0080_[0];
  assign _0075_[2] = _0081_[2] ^ _0080_[1];
  assign _0075_[3] = _0081_[3] ^ _0080_[2];
  assign _0075_[4] = _0081_[4] ^ _0080_[3];
  assign _0075_[5] = _0081_[5] ^ _0080_[4];
  assign _0075_[6] = _0081_[6] ^ _0080_[5];
  assign _0075_[7] = _0081_[7] ^ _0080_[6];
  assign _0075_[8] = _0081_[8] ^ _0080_[7];
  assign _0075_[9] = _0081_[9] ^ _0080_[8];
  assign _0075_[10] = _0081_[10] ^ _0080_[9];
  assign _0075_[11] = _0081_[11] ^ _0080_[10];
  assign _0075_[12] = _0081_[12] ^ _0080_[11];
  assign _0075_[13] = _0081_[13] ^ _0080_[12];
  assign _0075_[14] = _0081_[14] ^ _0080_[13];
  assign _0075_[15] = _0081_[15] ^ _0080_[14];
  assign _0075_[16] = _0081_[16] ^ _0080_[15];
  assign _0075_[17] = _0081_[17] ^ _0080_[16];
  assign _0075_[18] = _0081_[18] ^ _0080_[17];
  assign _0075_[19] = _0081_[19] ^ _0080_[18];
  assign _0075_[20] = _0081_[20] ^ _0080_[19];
  assign _0075_[21] = _0081_[21] ^ _0080_[20];
  assign _0075_[22] = _0081_[22] ^ _0080_[21];
  assign _0075_[23] = _0081_[23] ^ _0080_[22];
  assign _0075_[24] = _0081_[24] ^ _0080_[23];
  assign _0075_[25] = _0081_[25] ^ _0080_[24];
  assign _0075_[26] = _0081_[26] ^ _0080_[25];
  assign _0075_[27] = _0081_[27] ^ _0080_[26];
  assign _0075_[28] = _0081_[28] ^ _0080_[27];
  assign _0075_[29] = _0081_[29] ^ _0080_[28];
  assign _0075_[30] = _0081_[30] ^ _0080_[29];
  assign _0075_[31] = _0081_[31] ^ _0080_[30];
  assign _0081_[1] = imm_i[1] ^ operand_a_i[1];
  assign _0081_[2] = imm_i[2] ^ operand_a_i[2];
  assign _0081_[3] = imm_i[3] ^ operand_a_i[3];
  assign _0081_[4] = imm_i[4] ^ operand_a_i[4];
  assign _0081_[5] = imm_i[5] ^ operand_a_i[5];
  assign _0081_[6] = imm_i[6] ^ operand_a_i[6];
  assign _0081_[7] = imm_i[7] ^ operand_a_i[7];
  assign _0081_[8] = imm_i[8] ^ operand_a_i[8];
  assign _0081_[9] = imm_i[9] ^ operand_a_i[9];
  assign _0081_[10] = imm_i[10] ^ operand_a_i[10];
  assign _0081_[11] = imm_i[11] ^ operand_a_i[11];
  assign _0081_[12] = imm_i[12] ^ operand_a_i[12];
  assign _0081_[13] = imm_i[13] ^ operand_a_i[13];
  assign _0081_[14] = imm_i[14] ^ operand_a_i[14];
  assign _0081_[15] = imm_i[15] ^ operand_a_i[15];
  assign _0081_[16] = imm_i[16] ^ operand_a_i[16];
  assign _0081_[17] = imm_i[17] ^ operand_a_i[17];
  assign _0081_[18] = imm_i[18] ^ operand_a_i[18];
  assign _0081_[19] = imm_i[19] ^ operand_a_i[19];
  assign _0081_[20] = imm_i[20] ^ operand_a_i[20];
  assign _0081_[21] = imm_i[21] ^ operand_a_i[21];
  assign _0081_[22] = imm_i[22] ^ operand_a_i[22];
  assign _0081_[23] = imm_i[23] ^ operand_a_i[23];
  assign _0081_[24] = imm_i[24] ^ operand_a_i[24];
  assign _0081_[25] = imm_i[25] ^ operand_a_i[25];
  assign _0081_[26] = imm_i[26] ^ operand_a_i[26];
  assign _0081_[27] = imm_i[27] ^ operand_a_i[27];
  assign _0081_[28] = imm_i[28] ^ operand_a_i[28];
  assign _0081_[29] = imm_i[29] ^ operand_a_i[29];
  assign _0081_[30] = imm_i[30] ^ operand_a_i[30];
  assign _0081_[31] = imm_i[31] ^ operand_a_i[31];
  assign _0080_[0] = imm_i[0] & operand_a_i[0];
  assign _0082_[1] = imm_i[1] & operand_a_i[1];
  assign _0082_[2] = imm_i[2] & operand_a_i[2];
  assign _0082_[3] = imm_i[3] & operand_a_i[3];
  assign _0082_[4] = imm_i[4] & operand_a_i[4];
  assign _0082_[5] = imm_i[5] & operand_a_i[5];
  assign _0082_[6] = imm_i[6] & operand_a_i[6];
  assign _0082_[7] = imm_i[7] & operand_a_i[7];
  assign _0082_[8] = imm_i[8] & operand_a_i[8];
  assign _0082_[9] = imm_i[9] & operand_a_i[9];
  assign _0082_[10] = imm_i[10] & operand_a_i[10];
  assign _0082_[11] = imm_i[11] & operand_a_i[11];
  assign _0082_[12] = imm_i[12] & operand_a_i[12];
  assign _0082_[13] = imm_i[13] & operand_a_i[13];
  assign _0082_[14] = imm_i[14] & operand_a_i[14];
  assign _0082_[15] = imm_i[15] & operand_a_i[15];
  assign _0082_[16] = imm_i[16] & operand_a_i[16];
  assign _0082_[17] = imm_i[17] & operand_a_i[17];
  assign _0082_[18] = imm_i[18] & operand_a_i[18];
  assign _0082_[19] = imm_i[19] & operand_a_i[19];
  assign _0082_[20] = imm_i[20] & operand_a_i[20];
  assign _0082_[21] = imm_i[21] & operand_a_i[21];
  assign _0082_[22] = imm_i[22] & operand_a_i[22];
  assign _0082_[23] = imm_i[23] & operand_a_i[23];
  assign _0082_[24] = imm_i[24] & operand_a_i[24];
  assign _0082_[25] = imm_i[25] & operand_a_i[25];
  assign _0082_[26] = imm_i[26] & operand_a_i[26];
  assign _0082_[27] = imm_i[27] & operand_a_i[27];
  assign _0082_[28] = imm_i[28] & operand_a_i[28];
  assign _0082_[29] = imm_i[29] & operand_a_i[29];
  assign _0082_[30] = imm_i[30] & operand_a_i[30];
  assign _0070_[67] = pc_i[3] ^ pc_i[2];
  assign _0070_[68] = pc_i[4] ^ _0083_[3];
  assign _0070_[69] = pc_i[5] ^ _0083_[4];
  assign _0070_[70] = pc_i[6] ^ _0083_[5];
  assign _0070_[71] = pc_i[7] ^ _0083_[6];
  assign _0070_[72] = pc_i[8] ^ _0083_[7];
  assign _0070_[73] = pc_i[9] ^ _0083_[8];
  assign _0070_[74] = pc_i[10] ^ _0083_[9];
  assign _0070_[75] = pc_i[11] ^ _0083_[10];
  assign _0070_[76] = pc_i[12] ^ _0083_[11];
  assign _0070_[77] = pc_i[13] ^ _0083_[12];
  assign _0070_[78] = pc_i[14] ^ _0083_[13];
  assign _0070_[79] = pc_i[15] ^ _0083_[14];
  assign _0070_[80] = pc_i[16] ^ _0083_[15];
  assign _0070_[81] = pc_i[17] ^ _0083_[16];
  assign _0070_[82] = pc_i[18] ^ _0083_[17];
  assign _0070_[83] = pc_i[19] ^ _0083_[18];
  assign _0070_[84] = pc_i[20] ^ _0083_[19];
  assign _0070_[85] = pc_i[21] ^ _0083_[20];
  assign _0070_[86] = pc_i[22] ^ _0083_[21];
  assign _0070_[87] = pc_i[23] ^ _0083_[22];
  assign _0070_[88] = pc_i[24] ^ _0083_[23];
  assign _0070_[89] = pc_i[25] ^ _0083_[24];
  assign _0070_[90] = pc_i[26] ^ _0083_[25];
  assign _0070_[91] = pc_i[27] ^ _0083_[26];
  assign _0070_[92] = pc_i[28] ^ _0083_[27];
  assign _0070_[93] = pc_i[29] ^ _0083_[28];
  assign _0070_[94] = pc_i[30] ^ _0083_[29];
  assign _0070_[95] = pc_i[31] ^ _0083_[30];
  assign _0070_[1] = _0085_[1] ^ _0084_[0];
  assign _0070_[2] = _0085_[2] ^ _0084_[1];
  assign _0070_[3] = _0085_[3] ^ _0084_[2];
  assign _0070_[4] = _0085_[4] ^ _0084_[3];
  assign _0070_[5] = _0085_[5] ^ _0084_[4];
  assign _0070_[6] = _0085_[6] ^ _0084_[5];
  assign _0070_[7] = _0085_[7] ^ _0084_[6];
  assign _0070_[8] = _0085_[8] ^ _0084_[7];
  assign _0070_[9] = _0085_[9] ^ _0084_[8];
  assign _0070_[10] = _0085_[10] ^ _0084_[9];
  assign _0070_[11] = _0085_[11] ^ _0084_[10];
  assign _0070_[12] = _0085_[12] ^ _0084_[11];
  assign _0070_[13] = _0085_[13] ^ _0084_[12];
  assign _0070_[14] = _0085_[14] ^ _0084_[13];
  assign _0070_[15] = _0085_[15] ^ _0084_[14];
  assign _0070_[16] = _0085_[16] ^ _0084_[15];
  assign _0070_[17] = _0085_[17] ^ _0084_[16];
  assign _0070_[18] = _0085_[18] ^ _0084_[17];
  assign _0070_[19] = _0085_[19] ^ _0084_[18];
  assign _0070_[20] = _0085_[20] ^ _0084_[19];
  assign _0070_[21] = _0085_[21] ^ _0084_[20];
  assign _0070_[22] = _0085_[22] ^ _0084_[21];
  assign _0070_[23] = _0085_[23] ^ _0084_[22];
  assign _0070_[24] = _0085_[24] ^ _0084_[23];
  assign _0070_[25] = _0085_[25] ^ _0084_[24];
  assign _0070_[26] = _0085_[26] ^ _0084_[25];
  assign _0070_[27] = _0085_[27] ^ _0084_[26];
  assign _0070_[28] = _0085_[28] ^ _0084_[27];
  assign _0070_[29] = _0085_[29] ^ _0084_[28];
  assign _0070_[30] = _0085_[30] ^ _0084_[29];
  assign _0070_[31] = _0085_[31] ^ _0084_[30];
  assign _0070_[0] = imm_i[0] ^ pc_i[0];
  assign _0085_[1] = imm_i[1] ^ pc_i[1];
  assign _0085_[2] = imm_i[2] ^ pc_i[2];
  assign _0085_[3] = imm_i[3] ^ pc_i[3];
  assign _0085_[4] = imm_i[4] ^ pc_i[4];
  assign _0085_[5] = imm_i[5] ^ pc_i[5];
  assign _0085_[6] = imm_i[6] ^ pc_i[6];
  assign _0085_[7] = imm_i[7] ^ pc_i[7];
  assign _0085_[8] = imm_i[8] ^ pc_i[8];
  assign _0085_[9] = imm_i[9] ^ pc_i[9];
  assign _0085_[10] = imm_i[10] ^ pc_i[10];
  assign _0085_[11] = imm_i[11] ^ pc_i[11];
  assign _0085_[12] = imm_i[12] ^ pc_i[12];
  assign _0085_[13] = imm_i[13] ^ pc_i[13];
  assign _0085_[14] = imm_i[14] ^ pc_i[14];
  assign _0085_[15] = imm_i[15] ^ pc_i[15];
  assign _0085_[16] = imm_i[16] ^ pc_i[16];
  assign _0085_[17] = imm_i[17] ^ pc_i[17];
  assign _0085_[18] = imm_i[18] ^ pc_i[18];
  assign _0085_[19] = imm_i[19] ^ pc_i[19];
  assign _0085_[20] = imm_i[20] ^ pc_i[20];
  assign _0085_[21] = imm_i[21] ^ pc_i[21];
  assign _0085_[22] = imm_i[22] ^ pc_i[22];
  assign _0085_[23] = imm_i[23] ^ pc_i[23];
  assign _0085_[24] = imm_i[24] ^ pc_i[24];
  assign _0085_[25] = imm_i[25] ^ pc_i[25];
  assign _0085_[26] = imm_i[26] ^ pc_i[26];
  assign _0085_[27] = imm_i[27] ^ pc_i[27];
  assign _0085_[28] = imm_i[28] ^ pc_i[28];
  assign _0085_[29] = imm_i[29] ^ pc_i[29];
  assign _0085_[30] = imm_i[30] ^ pc_i[30];
  assign _0085_[31] = imm_i[31] ^ pc_i[31];
  assign _0084_[0] = imm_i[0] & pc_i[0];
  assign _0086_[1] = imm_i[1] & pc_i[1];
  assign _0086_[2] = imm_i[2] & pc_i[2];
  assign _0086_[3] = imm_i[3] & pc_i[3];
  assign _0086_[4] = imm_i[4] & pc_i[4];
  assign _0086_[5] = imm_i[5] & pc_i[5];
  assign _0086_[6] = imm_i[6] & pc_i[6];
  assign _0086_[7] = imm_i[7] & pc_i[7];
  assign _0086_[8] = imm_i[8] & pc_i[8];
  assign _0086_[9] = imm_i[9] & pc_i[9];
  assign _0086_[10] = imm_i[10] & pc_i[10];
  assign _0086_[11] = imm_i[11] & pc_i[11];
  assign _0086_[12] = imm_i[12] & pc_i[12];
  assign _0086_[13] = imm_i[13] & pc_i[13];
  assign _0086_[14] = imm_i[14] & pc_i[14];
  assign _0086_[15] = imm_i[15] & pc_i[15];
  assign _0086_[16] = imm_i[16] & pc_i[16];
  assign _0086_[17] = imm_i[17] & pc_i[17];
  assign _0086_[18] = imm_i[18] & pc_i[18];
  assign _0086_[19] = imm_i[19] & pc_i[19];
  assign _0086_[20] = imm_i[20] & pc_i[20];
  assign _0086_[21] = imm_i[21] & pc_i[21];
  assign _0086_[22] = imm_i[22] & pc_i[22];
  assign _0086_[23] = imm_i[23] & pc_i[23];
  assign _0086_[24] = imm_i[24] & pc_i[24];
  assign _0086_[25] = imm_i[25] & pc_i[25];
  assign _0086_[26] = imm_i[26] & pc_i[26];
  assign _0086_[27] = imm_i[27] & pc_i[27];
  assign _0086_[28] = imm_i[28] & pc_i[28];
  assign _0086_[29] = imm_i[29] & pc_i[29];
  assign _0086_[30] = imm_i[30] & pc_i[30];
  assign _0340_ = _0043_[1] & _0088_[7];
  assign _0341_ = _0043_[3] & _0370_;
  assign _0342_ = _0044_[1] & _0088_[15];
  assign _0344_ = _0042_[6] & _0088_[23];
  assign _0345_ = _0041_[14] & _0088_[27];
  assign _0346_ = _0089_[30] & _0088_[29];
  assign _0088_[31] = _0372_ | _0342_;
  assign _0088_[27] = _0367_ | _0344_;
  assign _0327_ = _0089_[31] & _0091_[30];
  assign _0328_ = _0041_[1] & _0088_[1];
  assign _0329_ = _0041_[3] & _0348_;
  assign _0330_ = _0041_[5] & _0350_;
  assign _0331_ = _0041_[7] & _0352_;
  assign _0332_ = _0041_[9] & _0354_;
  assign _0333_ = _0041_[11] & _0356_;
  assign _0334_ = _0041_[13] & _0358_;
  assign _0335_ = _0041_[15] & _0360_;
  assign _0336_ = _0042_[1] & _0088_[3];
  assign _0337_ = _0042_[3] & _0363_;
  assign _0338_ = _0042_[5] & _0365_;
  assign _0339_ = _0042_[7] & _0367_;
  assign _0041_[15] = _0089_[31] & _0089_[30];
  assign _0042_[1] = _0041_[3] & _0041_[2];
  assign _0042_[2] = _0041_[5] & _0041_[4];
  assign _0042_[3] = _0041_[7] & _0041_[6];
  assign _0042_[4] = _0041_[9] & _0041_[8];
  assign _0042_[5] = _0041_[11] & _0041_[10];
  assign _0042_[6] = _0041_[13] & _0041_[12];
  assign _0042_[7] = _0041_[15] & _0041_[14];
  assign _0043_[1] = _0042_[3] & _0042_[2];
  assign _0043_[2] = _0042_[5] & _0042_[4];
  assign _0043_[3] = _0042_[7] & _0042_[6];
  assign _0044_[1] = _0043_[3] & _0043_[2];
  assign _0343_ = _0043_[2] & _0088_[15];
  assign _0088_[1] = _0091_[1] | _0312_;
  assign _0347_ = _0091_[3] | _0313_;
  assign _0348_ = _0091_[5] | _0314_;
  assign _0349_ = _0091_[7] | _0315_;
  assign _0350_ = _0091_[9] | _0316_;
  assign _0351_ = _0091_[11] | _0317_;
  assign _0352_ = _0091_[13] | _0318_;
  assign _0353_ = _0091_[15] | _0319_;
  assign _0354_ = _0091_[17] | _0320_;
  assign _0355_ = _0091_[19] | _0321_;
  assign _0356_ = _0091_[21] | _0322_;
  assign _0357_ = _0091_[23] | _0323_;
  assign _0358_ = _0091_[25] | _0324_;
  assign _0359_ = _0091_[27] | _0325_;
  assign _0360_ = _0091_[29] | _0326_;
  assign _0361_ = _0091_[31] | _0327_;
  assign _0088_[3] = _0347_ | _0328_;
  assign _0362_ = _0349_ | _0329_;
  assign _0363_ = _0351_ | _0330_;
  assign _0364_ = _0353_ | _0331_;
  assign _0365_ = _0355_ | _0332_;
  assign _0366_ = _0357_ | _0333_;
  assign _0367_ = _0359_ | _0334_;
  assign _0088_[23] = _0370_ | _0343_;
  assign _0088_[29] = _0360_ | _0345_;
  assign _0312_ = _0089_[1] & _0088_[0];
  assign _0313_ = _0089_[3] & _0091_[2];
  assign _0314_ = _0089_[5] & _0091_[4];
  assign _0315_ = _0089_[7] & _0091_[6];
  assign _0316_ = _0089_[9] & _0091_[8];
  assign _0317_ = _0089_[11] & _0091_[10];
  assign _0318_ = _0089_[13] & _0091_[12];
  assign _0319_ = _0089_[15] & _0091_[14];
  assign _0320_ = _0089_[17] & _0091_[16];
  assign _0321_ = _0089_[19] & _0091_[18];
  assign _0322_ = _0089_[21] & _0091_[20];
  assign _0323_ = _0089_[23] & _0091_[22];
  assign _0324_ = _0089_[25] & _0091_[24];
  assign _0325_ = _0089_[27] & _0091_[26];
  assign _0326_ = _0089_[29] & _0091_[28];
  assign _0041_[1] = _0089_[3] & _0089_[2];
  assign _0041_[2] = _0089_[5] & _0089_[4];
  assign _0041_[3] = _0089_[7] & _0089_[6];
  assign _0041_[4] = _0089_[9] & _0089_[8];
  assign _0041_[5] = _0089_[11] & _0089_[10];
  assign _0041_[6] = _0089_[13] & _0089_[12];
  assign _0041_[7] = _0089_[15] & _0089_[14];
  assign _0041_[8] = _0089_[17] & _0089_[16];
  assign _0041_[9] = _0089_[19] & _0089_[18];
  assign _0041_[10] = _0089_[21] & _0089_[20];
  assign _0041_[11] = _0089_[23] & _0089_[22];
  assign _0041_[12] = _0089_[25] & _0089_[24];
  assign _0041_[13] = _0089_[27] & _0089_[26];
  assign _0041_[14] = _0089_[29] & _0089_[28];
  assign _0088_[0] = _0091_[0] | _0089_[0];
  assign _0368_ = _0361_ | _0335_;
  assign _0088_[7] = _0362_ | _0336_;
  assign _0369_ = _0364_ | _0337_;
  assign _0370_ = _0366_ | _0338_;
  assign _0371_ = _0368_ | _0339_;
  assign _0088_[15] = _0369_ | _0340_;
  assign _0372_ = _0371_ | _0341_;
  assign _0088_[30] = _0091_[30] | _0346_;
  assign _0099_ = _0081_[1] & _0080_[0];
  assign _0100_ = _0081_[3] & _0082_[2];
  assign _0101_ = _0081_[5] & _0082_[4];
  assign _0102_ = _0081_[7] & _0082_[6];
  assign _0103_ = _0081_[9] & _0082_[8];
  assign _0104_ = _0081_[11] & _0082_[10];
  assign _0105_ = _0081_[13] & _0082_[12];
  assign _0106_ = _0081_[15] & _0082_[14];
  assign _0107_ = _0081_[17] & _0082_[16];
  assign _0108_ = _0081_[19] & _0082_[18];
  assign _0109_ = _0081_[21] & _0082_[20];
  assign _0110_ = _0081_[23] & _0082_[22];
  assign _0111_ = _0081_[25] & _0082_[24];
  assign _0112_ = _0081_[27] & _0082_[26];
  assign _0113_ = _0081_[29] & _0082_[28];
  assign _0114_ = _0125_ & _0080_[1];
  assign _0115_ = _0127_ & _0174_;
  assign _0116_ = _0129_ & _0176_;
  assign _0117_ = _0131_ & _0178_;
  assign _0118_ = _0133_ & _0180_;
  assign _0119_ = _0135_ & _0182_;
  assign _0120_ = _0137_ & _0184_;
  assign _0121_ = _0139_ & _0080_[3];
  assign _0122_ = _0141_ & _0188_;
  assign _0123_ = _0143_ & _0190_;
  assign _0124_ = _0145_ & _0080_[7];
  assign _0125_ = _0081_[3] & _0081_[2];
  assign _0126_ = _0081_[5] & _0081_[4];
  assign _0127_ = _0081_[7] & _0081_[6];
  assign _0128_ = _0081_[9] & _0081_[8];
  assign _0129_ = _0081_[11] & _0081_[10];
  assign _0130_ = _0081_[13] & _0081_[12];
  assign _0131_ = _0081_[15] & _0081_[14];
  assign _0132_ = _0081_[17] & _0081_[16];
  assign _0133_ = _0081_[19] & _0081_[18];
  assign _0134_ = _0081_[21] & _0081_[20];
  assign _0135_ = _0081_[23] & _0081_[22];
  assign _0136_ = _0081_[25] & _0081_[24];
  assign _0137_ = _0081_[27] & _0081_[26];
  assign _0138_ = _0081_[29] & _0081_[28];
  assign _0139_ = _0127_ & _0126_;
  assign _0140_ = _0129_ & _0128_;
  assign _0141_ = _0131_ & _0130_;
  assign _0142_ = _0133_ & _0132_;
  assign _0143_ = _0135_ & _0134_;
  assign _0144_ = _0137_ & _0136_;
  assign _0145_ = _0141_ & _0140_;
  assign _0146_ = _0143_ & _0142_;
  assign _0147_ = _0146_ & _0080_[15];
  assign _0148_ = _0140_ & _0080_[7];
  assign _0149_ = _0142_ & _0080_[15];
  assign _0150_ = _0144_ & _0080_[23];
  assign _0151_ = _0126_ & _0080_[3];
  assign _0152_ = _0128_ & _0080_[7];
  assign _0153_ = _0130_ & _0080_[11];
  assign _0154_ = _0132_ & _0080_[15];
  assign _0155_ = _0134_ & _0080_[19];
  assign _0156_ = _0136_ & _0080_[23];
  assign _0157_ = _0138_ & _0080_[27];
  assign _0158_ = _0081_[2] & _0080_[1];
  assign _0159_ = _0081_[4] & _0080_[3];
  assign _0160_ = _0081_[6] & _0080_[5];
  assign _0161_ = _0081_[8] & _0080_[7];
  assign _0162_ = _0081_[10] & _0080_[9];
  assign _0163_ = _0081_[12] & _0080_[11];
  assign _0164_ = _0081_[14] & _0080_[13];
  assign _0165_ = _0081_[16] & _0080_[15];
  assign _0166_ = _0081_[18] & _0080_[17];
  assign _0167_ = _0081_[20] & _0080_[19];
  assign _0168_ = _0081_[22] & _0080_[21];
  assign _0169_ = _0081_[24] & _0080_[23];
  assign _0170_ = _0081_[26] & _0080_[25];
  assign _0171_ = _0081_[28] & _0080_[27];
  assign _0172_ = _0081_[30] & _0080_[29];
  assign _0080_[1] = _0082_[1] | _0099_;
  assign _0173_ = _0082_[3] | _0100_;
  assign _0174_ = _0082_[5] | _0101_;
  assign _0175_ = _0082_[7] | _0102_;
  assign _0176_ = _0082_[9] | _0103_;
  assign _0177_ = _0082_[11] | _0104_;
  assign _0178_ = _0082_[13] | _0105_;
  assign _0179_ = _0082_[15] | _0106_;
  assign _0180_ = _0082_[17] | _0107_;
  assign _0181_ = _0082_[19] | _0108_;
  assign _0182_ = _0082_[21] | _0109_;
  assign _0183_ = _0082_[23] | _0110_;
  assign _0184_ = _0082_[25] | _0111_;
  assign _0185_ = _0082_[27] | _0112_;
  assign _0186_ = _0082_[29] | _0113_;
  assign _0080_[3] = _0173_ | _0114_;
  assign _0187_ = _0175_ | _0115_;
  assign _0188_ = _0177_ | _0116_;
  assign _0189_ = _0179_ | _0117_;
  assign _0190_ = _0181_ | _0118_;
  assign _0191_ = _0183_ | _0119_;
  assign _0192_ = _0185_ | _0120_;
  assign _0080_[7] = _0187_ | _0121_;
  assign _0193_ = _0189_ | _0122_;
  assign _0194_ = _0191_ | _0123_;
  assign _0080_[15] = _0193_ | _0124_;
  assign _0080_[23] = _0194_ | _0147_;
  assign _0080_[11] = _0188_ | _0148_;
  assign _0080_[19] = _0190_ | _0149_;
  assign _0080_[27] = _0192_ | _0150_;
  assign _0080_[5] = _0174_ | _0151_;
  assign _0080_[9] = _0176_ | _0152_;
  assign _0080_[13] = _0178_ | _0153_;
  assign _0080_[17] = _0180_ | _0154_;
  assign _0080_[21] = _0182_ | _0155_;
  assign _0080_[25] = _0184_ | _0156_;
  assign _0080_[29] = _0186_ | _0157_;
  assign _0080_[2] = _0082_[2] | _0158_;
  assign _0080_[4] = _0082_[4] | _0159_;
  assign _0080_[6] = _0082_[6] | _0160_;
  assign _0080_[8] = _0082_[8] | _0161_;
  assign _0080_[10] = _0082_[10] | _0162_;
  assign _0080_[12] = _0082_[12] | _0163_;
  assign _0080_[14] = _0082_[14] | _0164_;
  assign _0080_[16] = _0082_[16] | _0165_;
  assign _0080_[18] = _0082_[18] | _0166_;
  assign _0080_[20] = _0082_[20] | _0167_;
  assign _0080_[22] = _0082_[22] | _0168_;
  assign _0080_[24] = _0082_[24] | _0169_;
  assign _0080_[26] = _0082_[26] | _0170_;
  assign _0080_[28] = _0082_[28] | _0171_;
  assign _0080_[30] = _0082_[30] | _0172_;
  assign _0083_[3] = pc_i[3] & pc_i[2];
  assign _0083_[7] = _0208_ & _0083_[3];
  assign _0083_[15] = _0214_ & _0083_[7];
  assign _0195_ = pc_i[5] & pc_i[4];
  assign _0196_ = pc_i[7] & pc_i[6];
  assign _0197_ = pc_i[9] & pc_i[8];
  assign _0198_ = pc_i[11] & pc_i[10];
  assign _0199_ = pc_i[13] & pc_i[12];
  assign _0200_ = pc_i[15] & pc_i[14];
  assign _0201_ = pc_i[17] & pc_i[16];
  assign _0202_ = pc_i[19] & pc_i[18];
  assign _0203_ = pc_i[21] & pc_i[20];
  assign _0204_ = pc_i[23] & pc_i[22];
  assign _0205_ = pc_i[25] & pc_i[24];
  assign _0206_ = pc_i[27] & pc_i[26];
  assign _0207_ = pc_i[29] & pc_i[28];
  assign _0208_ = _0196_ & _0195_;
  assign _0209_ = _0198_ & _0197_;
  assign _0210_ = _0200_ & _0199_;
  assign _0211_ = _0202_ & _0201_;
  assign _0212_ = _0204_ & _0203_;
  assign _0213_ = _0206_ & _0205_;
  assign _0214_ = _0210_ & _0209_;
  assign _0215_ = _0212_ & _0211_;
  assign _0083_[23] = _0215_ & _0083_[15];
  assign _0083_[11] = _0209_ & _0083_[7];
  assign _0083_[19] = _0211_ & _0083_[15];
  assign _0083_[27] = _0213_ & _0083_[23];
  assign _0083_[5] = _0195_ & _0083_[3];
  assign _0083_[9] = _0197_ & _0083_[7];
  assign _0083_[13] = _0199_ & _0083_[11];
  assign _0083_[17] = _0201_ & _0083_[15];
  assign _0083_[21] = _0203_ & _0083_[19];
  assign _0083_[25] = _0205_ & _0083_[23];
  assign _0083_[29] = _0207_ & _0083_[27];
  assign _0083_[4] = pc_i[4] & _0083_[3];
  assign _0083_[6] = pc_i[6] & _0083_[5];
  assign _0083_[8] = pc_i[8] & _0083_[7];
  assign _0083_[10] = pc_i[10] & _0083_[9];
  assign _0083_[12] = pc_i[12] & _0083_[11];
  assign _0083_[14] = pc_i[14] & _0083_[13];
  assign _0083_[16] = pc_i[16] & _0083_[15];
  assign _0083_[18] = pc_i[18] & _0083_[17];
  assign _0083_[20] = pc_i[20] & _0083_[19];
  assign _0083_[22] = pc_i[22] & _0083_[21];
  assign _0083_[24] = pc_i[24] & _0083_[23];
  assign _0083_[26] = pc_i[26] & _0083_[25];
  assign _0083_[28] = pc_i[28] & _0083_[27];
  assign _0083_[30] = pc_i[30] & _0083_[29];
  assign _0216_ = _0085_[1] & _0084_[0];
  assign _0217_ = _0085_[3] & _0086_[2];
  assign _0218_ = _0085_[5] & _0086_[4];
  assign _0219_ = _0085_[7] & _0086_[6];
  assign _0220_ = _0085_[9] & _0086_[8];
  assign _0221_ = _0085_[11] & _0086_[10];
  assign _0222_ = _0085_[13] & _0086_[12];
  assign _0223_ = _0085_[15] & _0086_[14];
  assign _0224_ = _0085_[17] & _0086_[16];
  assign _0225_ = _0085_[19] & _0086_[18];
  assign _0226_ = _0085_[21] & _0086_[20];
  assign _0227_ = _0085_[23] & _0086_[22];
  assign _0228_ = _0085_[25] & _0086_[24];
  assign _0229_ = _0085_[27] & _0086_[26];
  assign _0230_ = _0085_[29] & _0086_[28];
  assign _0231_ = _0242_ & _0084_[1];
  assign _0232_ = _0244_ & _0291_;
  assign _0233_ = _0246_ & _0293_;
  assign _0234_ = _0248_ & _0295_;
  assign _0235_ = _0250_ & _0297_;
  assign _0236_ = _0252_ & _0299_;
  assign _0237_ = _0254_ & _0301_;
  assign _0238_ = _0256_ & _0084_[3];
  assign _0239_ = _0258_ & _0305_;
  assign _0240_ = _0260_ & _0307_;
  assign _0241_ = _0262_ & _0084_[7];
  assign _0242_ = _0085_[3] & _0085_[2];
  assign _0243_ = _0085_[5] & _0085_[4];
  assign _0244_ = _0085_[7] & _0085_[6];
  assign _0245_ = _0085_[9] & _0085_[8];
  assign _0246_ = _0085_[11] & _0085_[10];
  assign _0247_ = _0085_[13] & _0085_[12];
  assign _0248_ = _0085_[15] & _0085_[14];
  assign _0249_ = _0085_[17] & _0085_[16];
  assign _0250_ = _0085_[19] & _0085_[18];
  assign _0251_ = _0085_[21] & _0085_[20];
  assign _0252_ = _0085_[23] & _0085_[22];
  assign _0253_ = _0085_[25] & _0085_[24];
  assign _0254_ = _0085_[27] & _0085_[26];
  assign _0255_ = _0085_[29] & _0085_[28];
  assign _0256_ = _0244_ & _0243_;
  assign _0257_ = _0246_ & _0245_;
  assign _0258_ = _0248_ & _0247_;
  assign _0259_ = _0250_ & _0249_;
  assign _0260_ = _0252_ & _0251_;
  assign _0261_ = _0254_ & _0253_;
  assign _0262_ = _0258_ & _0257_;
  assign _0263_ = _0260_ & _0259_;
  assign _0264_ = _0263_ & _0084_[15];
  assign _0265_ = _0257_ & _0084_[7];
  assign _0266_ = _0259_ & _0084_[15];
  assign _0267_ = _0261_ & _0084_[23];
  assign _0268_ = _0243_ & _0084_[3];
  assign _0269_ = _0245_ & _0084_[7];
  assign _0270_ = _0247_ & _0084_[11];
  assign _0271_ = _0249_ & _0084_[15];
  assign _0272_ = _0251_ & _0084_[19];
  assign _0273_ = _0253_ & _0084_[23];
  assign _0274_ = _0255_ & _0084_[27];
  assign _0275_ = _0085_[2] & _0084_[1];
  assign _0276_ = _0085_[4] & _0084_[3];
  assign _0277_ = _0085_[6] & _0084_[5];
  assign _0278_ = _0085_[8] & _0084_[7];
  assign _0279_ = _0085_[10] & _0084_[9];
  assign _0280_ = _0085_[12] & _0084_[11];
  assign _0281_ = _0085_[14] & _0084_[13];
  assign _0282_ = _0085_[16] & _0084_[15];
  assign _0283_ = _0085_[18] & _0084_[17];
  assign _0284_ = _0085_[20] & _0084_[19];
  assign _0285_ = _0085_[22] & _0084_[21];
  assign _0286_ = _0085_[24] & _0084_[23];
  assign _0287_ = _0085_[26] & _0084_[25];
  assign _0288_ = _0085_[28] & _0084_[27];
  assign _0289_ = _0085_[30] & _0084_[29];
  assign _0084_[1] = _0086_[1] | _0216_;
  assign _0290_ = _0086_[3] | _0217_;
  assign _0291_ = _0086_[5] | _0218_;
  assign _0292_ = _0086_[7] | _0219_;
  assign _0293_ = _0086_[9] | _0220_;
  assign _0294_ = _0086_[11] | _0221_;
  assign _0295_ = _0086_[13] | _0222_;
  assign _0296_ = _0086_[15] | _0223_;
  assign _0297_ = _0086_[17] | _0224_;
  assign _0298_ = _0086_[19] | _0225_;
  assign _0299_ = _0086_[21] | _0226_;
  assign _0300_ = _0086_[23] | _0227_;
  assign _0301_ = _0086_[25] | _0228_;
  assign _0302_ = _0086_[27] | _0229_;
  assign _0303_ = _0086_[29] | _0230_;
  assign _0084_[3] = _0290_ | _0231_;
  assign _0304_ = _0292_ | _0232_;
  assign _0305_ = _0294_ | _0233_;
  assign _0306_ = _0296_ | _0234_;
  assign _0307_ = _0298_ | _0235_;
  assign _0308_ = _0300_ | _0236_;
  assign _0309_ = _0302_ | _0237_;
  assign _0084_[7] = _0304_ | _0238_;
  assign _0310_ = _0306_ | _0239_;
  assign _0311_ = _0308_ | _0240_;
  assign _0084_[15] = _0310_ | _0241_;
  assign _0084_[23] = _0311_ | _0264_;
  assign _0084_[11] = _0305_ | _0265_;
  assign _0084_[19] = _0307_ | _0266_;
  assign _0084_[27] = _0309_ | _0267_;
  assign _0084_[5] = _0291_ | _0268_;
  assign _0084_[9] = _0293_ | _0269_;
  assign _0084_[13] = _0295_ | _0270_;
  assign _0084_[17] = _0297_ | _0271_;
  assign _0084_[21] = _0299_ | _0272_;
  assign _0084_[25] = _0301_ | _0273_;
  assign _0084_[29] = _0303_ | _0274_;
  assign _0084_[2] = _0086_[2] | _0275_;
  assign _0084_[4] = _0086_[4] | _0276_;
  assign _0084_[6] = _0086_[6] | _0277_;
  assign _0084_[8] = _0086_[8] | _0278_;
  assign _0084_[10] = _0086_[10] | _0279_;
  assign _0084_[12] = _0086_[12] | _0280_;
  assign _0084_[14] = _0086_[14] | _0281_;
  assign _0084_[16] = _0086_[16] | _0282_;
  assign _0084_[18] = _0086_[18] | _0283_;
  assign _0084_[20] = _0086_[20] | _0284_;
  assign _0084_[22] = _0086_[22] | _0285_;
  assign _0084_[24] = _0086_[24] | _0286_;
  assign _0084_[26] = _0086_[26] | _0287_;
  assign _0084_[28] = _0086_[28] | _0288_;
  assign _0084_[30] = _0086_[30] | _0289_;
  assign _0070_[160] = _0094_ | _0092_;
  assign _0094_ = _0093_ ^ _0090_[31];
  assign _0093_ = _0088_[31] ^ _0088_[30];
  assign _0070_[96] = _0095_ | _0092_;
  assign _0004_[3:1] = { 2'h0, _0071_[81] };
  assign _0005_[3:1] = { 2'h0, _0071_[80] };
  assign _0006_[3:1] = { 2'h0, _0071_[79] };
  assign _0007_[3:1] = { 2'h0, _0071_[78] };
  assign _0008_[3:1] = { 2'h0, _0071_[77] };
  assign _0009_[3:1] = { 2'h0, _0071_[76] };
  assign _0010_[3:1] = { 2'h0, _0071_[75] };
  assign _0011_[3:1] = { 2'h0, _0071_[74] };
  assign _0012_[3:1] = { 2'h0, _0071_[73] };
  assign _0013_[3:1] = { 2'h0, _0071_[72] };
  assign _0014_[3:1] = { 2'h0, _0071_[71] };
  assign _0015_[3:1] = { 2'h0, _0071_[70] };
  assign _0016_[3:1] = { 2'h0, _0071_[69] };
  assign _0017_[3:1] = { 2'h0, _0071_[68] };
  assign _0018_[3:1] = { 2'h0, _0071_[67] };
  assign _0019_[3:1] = { 2'h0, _0071_[66] };
  assign _0020_[3:1] = { 2'h0, _0071_[65] };
  assign _0027_[2:1] = _0021_[3:2];
  assign _0034_[2:1] = _0024_[3:2];
  assign _0035_[1] = _0029_[1];
  assign _0037_[1] = _0036_[1];
  assign _0039_[1] = _0038_[1];
  assign _0040_[0] = _0038_[0];
  assign _0045_[3:1] = { 2'h0, _0071_[95] };
  assign _0046_[3:1] = { 2'h0, _0071_[94] };
  assign _0047_[3:1] = { 2'h0, _0071_[93] };
  assign _0048_[3:1] = { 2'h0, _0071_[92] };
  assign _0049_[3:1] = { 2'h0, _0071_[91] };
  assign _0050_[3:1] = { 2'h0, _0071_[90] };
  assign _0051_[3:1] = { 2'h0, _0071_[89] };
  assign _0052_[3:1] = { 2'h0, _0071_[88] };
  assign _0053_[3:1] = { 2'h0, _0071_[87] };
  assign _0054_[3:1] = { 2'h0, _0071_[86] };
  assign _0055_[3:1] = { 2'h0, _0071_[85] };
  assign _0056_[3:1] = { 2'h0, _0071_[84] };
  assign _0057_[3:1] = { 2'h0, _0071_[83] };
  assign _0058_[3:1] = { 2'h0, _0071_[82] };
  assign { _0070_[287:257], _0070_[255:225], _0070_[223:193], _0070_[191:161], _0070_[159:129], _0070_[127:97], _0070_[65:32] } = { 186'h00000000000000000000000000000000000000000000000, pc_i[1:0], imm_i };
  assign { _0071_[287:257], _0071_[255:225], _0071_[223:193], _0071_[191:161], _0071_[159:129], _0071_[127:97] } = 186'h00000000000000000000000000000000000000000000000;
  assign { _0075_[63:32], _0075_[0] } = { _0070_[31:0], 1'h0 };
  assign _0076_[0] = 1'h0;
  assign _0078_[0] = _0076_[32];
  assign _0082_[0] = _0080_[0];
  assign _0083_[2:0] = { pc_i[2], 2'h0 };
  assign _0085_[0] = _0070_[0];
  assign _0086_[0] = _0084_[0];
  assign exception_o = 1'h0;
  assign ready_o = 1'h1;
endmodule
