/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module l1_icache(clk, rst_n, req_valid_i, req_addr_i, req_ready_o, resp_valid_o, resp_data_o, resp_error_o, resp_ready_i, l2_req_valid_o, l2_req_addr_o, l2_req_ready_i, l2_resp_valid_i, l2_resp_data_i, l2_resp_error_i, l2_resp_ready_o, flush_i);
  wire [31:0] _000_;
  wire [2:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire [1:0] _086_;
  wire _087_;
  wire [1:0] _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire [1:0] _098_;
  wire _099_;
  wire [1:0] _100_;
  wire _101_;
  wire [1:0] _102_;
  wire _103_;
  wire _104_;
  wire [1:0] _105_;
  wire [1:0] _106_;
  wire _107_;
  wire [2:0] _108_;
  wire [2:0] _109_;
  wire [2:0] _110_;
  wire _111_;
  wire _112_;
  wire [1:0] _113_;
  wire _114_;
  wire [14:0] _115_;
  wire [14:0] _116_;
  wire [2:0] _117_;
  wire _118_;
  wire _119_;
  wire [6143:0] _120_;
  wire [6143:0] _121_;
  input clk;
  wire clk;
  input flush_i;
  wire flush_i;
  wire [63:0] hit_word_data;
  output [31:0] l2_req_addr_o;
  wire [31:0] l2_req_addr_o;
  input l2_req_ready_i;
  wire l2_req_ready_i;
  output l2_req_valid_o;
  wire l2_req_valid_o;
  input [511:0] l2_resp_data_i;
  wire [511:0] l2_resp_data_i;
  input l2_resp_error_i;
  wire l2_resp_error_i;
  output l2_resp_ready_o;
  wire l2_resp_ready_o;
  input l2_resp_valid_i;
  wire l2_resp_valid_i;
  wire [2:0] next_state;
  input [31:0] req_addr_i;
  wire [31:0] req_addr_i;
  output req_ready_o;
  wire req_ready_o;
  input req_valid_i;
  wire req_valid_i;
  output [31:0] resp_data_o;
  wire [31:0] resp_data_o;
  output resp_error_o;
  wire resp_error_o;
  input resp_ready_i;
  wire resp_ready_i;
  output resp_valid_o;
  wire resp_valid_o;
  input rst_n;
  wire rst_n;
  wire [2047:0] sram_dout;
  wire [2:0] state;
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(clk),
    .D(_021_),
    .Q(state[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(clk),
    .D(_022_),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(clk),
    .D(_023_),
    .Q(state[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(clk),
    .D(_024_),
    .Q(resp_valid_o),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(clk),
    .D(_025_),
    .Q(resp_data_o[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(clk),
    .D(_026_),
    .Q(resp_data_o[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(clk),
    .D(_027_),
    .Q(resp_data_o[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(clk),
    .D(_028_),
    .Q(resp_data_o[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(clk),
    .D(_029_),
    .Q(resp_data_o[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(clk),
    .D(_030_),
    .Q(resp_data_o[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(clk),
    .D(_031_),
    .Q(resp_data_o[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _133_ (
    .CLK(clk),
    .D(_032_),
    .Q(resp_data_o[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _134_ (
    .CLK(clk),
    .D(_033_),
    .Q(resp_data_o[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _135_ (
    .CLK(clk),
    .D(_034_),
    .Q(resp_data_o[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _136_ (
    .CLK(clk),
    .D(_035_),
    .Q(resp_data_o[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _137_ (
    .CLK(clk),
    .D(_036_),
    .Q(resp_data_o[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _138_ (
    .CLK(clk),
    .D(_037_),
    .Q(resp_data_o[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _139_ (
    .CLK(clk),
    .D(_038_),
    .Q(resp_data_o[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _140_ (
    .CLK(clk),
    .D(_039_),
    .Q(resp_data_o[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _141_ (
    .CLK(clk),
    .D(_040_),
    .Q(resp_data_o[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _142_ (
    .CLK(clk),
    .D(_041_),
    .Q(resp_data_o[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _143_ (
    .CLK(clk),
    .D(_042_),
    .Q(resp_data_o[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(clk),
    .D(_043_),
    .Q(resp_data_o[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _145_ (
    .CLK(clk),
    .D(_044_),
    .Q(resp_data_o[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _146_ (
    .CLK(clk),
    .D(_045_),
    .Q(resp_data_o[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _147_ (
    .CLK(clk),
    .D(_046_),
    .Q(resp_data_o[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _148_ (
    .CLK(clk),
    .D(_047_),
    .Q(resp_data_o[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _149_ (
    .CLK(clk),
    .D(_048_),
    .Q(resp_data_o[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _150_ (
    .CLK(clk),
    .D(_049_),
    .Q(resp_data_o[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _151_ (
    .CLK(clk),
    .D(_050_),
    .Q(resp_data_o[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _152_ (
    .CLK(clk),
    .D(_051_),
    .Q(resp_data_o[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _153_ (
    .CLK(clk),
    .D(_052_),
    .Q(resp_data_o[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _154_ (
    .CLK(clk),
    .D(_053_),
    .Q(resp_data_o[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _155_ (
    .CLK(clk),
    .D(_054_),
    .Q(resp_data_o[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _156_ (
    .CLK(clk),
    .D(_055_),
    .Q(resp_data_o[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _157_ (
    .CLK(clk),
    .D(_056_),
    .Q(resp_data_o[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _158_ (
    .CLK(clk),
    .D(_057_),
    .Q(l2_req_addr_o[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _159_ (
    .CLK(clk),
    .D(_058_),
    .Q(l2_req_addr_o[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _160_ (
    .CLK(clk),
    .D(_059_),
    .Q(l2_req_addr_o[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _161_ (
    .CLK(clk),
    .D(_060_),
    .Q(l2_req_addr_o[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _162_ (
    .CLK(clk),
    .D(_061_),
    .Q(l2_req_addr_o[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _163_ (
    .CLK(clk),
    .D(_062_),
    .Q(l2_req_addr_o[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(clk),
    .D(_063_),
    .Q(l2_req_addr_o[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(clk),
    .D(_064_),
    .Q(l2_req_addr_o[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(_065_),
    .Q(l2_req_addr_o[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(_066_),
    .Q(l2_req_addr_o[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_067_),
    .Q(l2_req_addr_o[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_068_),
    .Q(l2_req_addr_o[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_069_),
    .Q(l2_req_addr_o[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _171_ (
    .CLK(clk),
    .D(_070_),
    .Q(l2_req_addr_o[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(clk),
    .D(_071_),
    .Q(l2_req_addr_o[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(clk),
    .D(_072_),
    .Q(l2_req_addr_o[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(clk),
    .D(_073_),
    .Q(l2_req_addr_o[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(clk),
    .D(_074_),
    .Q(l2_req_addr_o[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _176_ (
    .CLK(clk),
    .D(_075_),
    .Q(l2_req_addr_o[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _177_ (
    .CLK(clk),
    .D(_076_),
    .Q(l2_req_addr_o[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _178_ (
    .CLK(clk),
    .D(_077_),
    .Q(l2_req_addr_o[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _179_ (
    .CLK(clk),
    .D(_078_),
    .Q(l2_req_addr_o[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _180_ (
    .CLK(clk),
    .D(_079_),
    .Q(l2_req_addr_o[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _181_ (
    .CLK(clk),
    .D(_080_),
    .Q(l2_req_addr_o[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _182_ (
    .CLK(clk),
    .D(_081_),
    .Q(l2_req_addr_o[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _183_ (
    .CLK(clk),
    .D(_082_),
    .Q(l2_req_addr_o[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _184_ (
    .CLK(clk),
    .D(_083_),
    .Q(l2_req_valid_o),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _185_ (
    .CLK(clk),
    .D(_084_),
    .Q(req_ready_o),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _186_ (
    .CLK(clk),
    .D(_085_),
    .Q(l2_resp_ready_o),
    .RESET_B(rst_n)
  );
  assign _021_ = _012_ ? _001_[0] : state[0];
  assign _022_ = _012_ ? _001_[1] : state[1];
  assign _023_ = _012_ ? _001_[2] : state[2];
  assign _024_ = _013_ ? _111_ : resp_valid_o;
  assign _025_ = _014_ ? _000_[0] : resp_data_o[0];
  assign _026_ = _014_ ? _000_[1] : resp_data_o[1];
  assign _027_ = _014_ ? _000_[2] : resp_data_o[2];
  assign _028_ = _014_ ? _000_[3] : resp_data_o[3];
  assign _029_ = _014_ ? _000_[4] : resp_data_o[4];
  assign _030_ = _014_ ? _000_[5] : resp_data_o[5];
  assign _031_ = _014_ ? _000_[6] : resp_data_o[6];
  assign _032_ = _014_ ? _000_[7] : resp_data_o[7];
  assign _033_ = _014_ ? _000_[8] : resp_data_o[8];
  assign _034_ = _014_ ? _000_[9] : resp_data_o[9];
  assign _035_ = _014_ ? _000_[10] : resp_data_o[10];
  assign _036_ = _014_ ? _000_[11] : resp_data_o[11];
  assign _037_ = _014_ ? _000_[12] : resp_data_o[12];
  assign _038_ = _014_ ? _000_[13] : resp_data_o[13];
  assign _039_ = _014_ ? _000_[14] : resp_data_o[14];
  assign _040_ = _014_ ? _000_[15] : resp_data_o[15];
  assign _041_ = _014_ ? _000_[16] : resp_data_o[16];
  assign _042_ = _014_ ? _000_[17] : resp_data_o[17];
  assign _043_ = _014_ ? _000_[18] : resp_data_o[18];
  assign _044_ = _014_ ? _000_[19] : resp_data_o[19];
  assign _045_ = _014_ ? _000_[20] : resp_data_o[20];
  assign _046_ = _014_ ? _000_[21] : resp_data_o[21];
  assign _047_ = _014_ ? _000_[22] : resp_data_o[22];
  assign _048_ = _014_ ? _000_[23] : resp_data_o[23];
  assign _049_ = _014_ ? _000_[24] : resp_data_o[24];
  assign _050_ = _014_ ? _000_[25] : resp_data_o[25];
  assign _051_ = _014_ ? _000_[26] : resp_data_o[26];
  assign _052_ = _014_ ? _000_[27] : resp_data_o[27];
  assign _053_ = _014_ ? _000_[28] : resp_data_o[28];
  assign _054_ = _014_ ? _000_[29] : resp_data_o[29];
  assign _055_ = _014_ ? _000_[30] : resp_data_o[30];
  assign _056_ = _014_ ? _000_[31] : resp_data_o[31];
  assign _084_ = _007_ ? _114_ : req_ready_o;
  assign _085_ = _006_ ? _107_ : l2_resp_ready_o;
  assign _057_ = _009_ ? l2_req_addr_o[6] : req_addr_i[6];
  assign _058_ = _009_ ? l2_req_addr_o[7] : req_addr_i[7];
  assign _059_ = _009_ ? l2_req_addr_o[8] : req_addr_i[8];
  assign _060_ = _009_ ? l2_req_addr_o[9] : req_addr_i[9];
  assign _061_ = _009_ ? l2_req_addr_o[10] : req_addr_i[10];
  assign _062_ = _009_ ? l2_req_addr_o[11] : req_addr_i[11];
  assign _063_ = _009_ ? l2_req_addr_o[12] : req_addr_i[12];
  assign _064_ = _009_ ? l2_req_addr_o[13] : req_addr_i[13];
  assign _065_ = _009_ ? l2_req_addr_o[14] : req_addr_i[14];
  assign _066_ = _009_ ? l2_req_addr_o[15] : req_addr_i[15];
  assign _067_ = _009_ ? l2_req_addr_o[16] : req_addr_i[16];
  assign _068_ = _009_ ? l2_req_addr_o[17] : req_addr_i[17];
  assign _069_ = _009_ ? l2_req_addr_o[18] : req_addr_i[18];
  assign _070_ = _009_ ? l2_req_addr_o[19] : req_addr_i[19];
  assign _071_ = _009_ ? l2_req_addr_o[20] : req_addr_i[20];
  assign _072_ = _009_ ? l2_req_addr_o[21] : req_addr_i[21];
  assign _073_ = _009_ ? l2_req_addr_o[22] : req_addr_i[22];
  assign _074_ = _009_ ? l2_req_addr_o[23] : req_addr_i[23];
  assign _075_ = _009_ ? l2_req_addr_o[24] : req_addr_i[24];
  assign _076_ = _009_ ? l2_req_addr_o[25] : req_addr_i[25];
  assign _077_ = _009_ ? l2_req_addr_o[26] : req_addr_i[26];
  assign _078_ = _009_ ? l2_req_addr_o[27] : req_addr_i[27];
  assign _079_ = _009_ ? l2_req_addr_o[28] : req_addr_i[28];
  assign _080_ = _009_ ? l2_req_addr_o[29] : req_addr_i[29];
  assign _081_ = _009_ ? l2_req_addr_o[30] : req_addr_i[30];
  assign _082_ = _009_ ? l2_req_addr_o[31] : req_addr_i[31];
  assign _083_ = _009_ ? l2_req_valid_o : 1'h1;
  assign _015_ = ~state[0];
  assign _016_ = ~state[1];
  assign _017_ = ~state[2];
  assign _086_[0] = _110_[0] | _106_[0];
  assign _086_[1] = _105_[1] | _113_[0];
  assign _087_ = _086_[0] | _086_[1];
  assign _119_ = _087_ | _110_[2];
  assign _088_[0] = _004_ & _005_;
  assign _088_[1] = _002_ & _003_;
  assign _012_ = _088_[0] & _088_[1];
  assign _011_ = _106_[0] | _113_[0];
  assign _006_ = _106_[0] | _105_[1];
  assign _014_ = _011_ & _009_;
  assign _008_ = resp_ready_i | _018_;
  assign _089_ = resp_ready_i | flush_i;
  assign _003_ = _089_ | _018_;
  assign _090_ = l2_req_ready_i | flush_i;
  assign _004_ = _090_ | _009_;
  assign _091_ = l2_resp_valid_i | flush_i;
  assign _005_ = _091_ | _020_;
  assign _007_ = _113_[0] | _110_[2];
  assign _010_ = _086_[0] | _007_;
  assign _092_ = req_valid_i | flush_i;
  assign _002_ = _092_ | _019_;
  assign _093_ = _008_ & _009_;
  assign _013_ = _093_ & _010_;
  assign _018_ = _094_ | _017_;
  assign _095_ = _015_ | _016_;
  assign _104_ = _095_ | state[2];
  assign _096_ = state[0] | _016_;
  assign _020_ = _096_ | state[2];
  assign _097_ = _015_ | state[1];
  assign _009_ = _097_ | state[2];
  assign _098_[1] = _116_[7] | _116_[11];
  assign _099_ = _109_[0] | _098_[1];
  assign _117_[0] = _099_ | _116_[12];
  assign _100_[1] = _116_[7] | _116_[10];
  assign _101_ = _109_[0] | _100_[1];
  assign _117_[1] = _101_ | _116_[14];
  assign _102_[1] = _116_[8] | _116_[11];
  assign _103_ = _112_ | _102_[1];
  assign _117_[2] = _103_ | _116_[14];
  assign _118_ = _086_[0] | _110_[2];
  assign _112_ = _109_[0] | _106_[0];
  assign _094_ = state[0] | state[1];
  assign _019_ = _094_ | state[2];
  assign _110_[0] = ~_018_;
  assign _106_[0] = ~_104_;
  assign _105_[1] = ~_020_;
  assign _113_[0] = ~_009_;
  assign _110_[2] = ~_019_;
  assign _121_[0] = req_addr_i[4] ? _120_[128] : _120_[0];
  assign _121_[1] = req_addr_i[4] ? _120_[129] : _120_[1];
  assign _121_[2] = req_addr_i[4] ? _120_[130] : _120_[2];
  assign _121_[3] = req_addr_i[4] ? _120_[131] : _120_[3];
  assign _121_[4] = req_addr_i[4] ? _120_[132] : _120_[4];
  assign _121_[5] = req_addr_i[4] ? _120_[133] : _120_[5];
  assign _121_[6] = req_addr_i[4] ? _120_[134] : _120_[6];
  assign _121_[7] = req_addr_i[4] ? _120_[135] : _120_[7];
  assign _121_[8] = req_addr_i[4] ? _120_[136] : _120_[8];
  assign _121_[9] = req_addr_i[4] ? _120_[137] : _120_[9];
  assign _121_[10] = req_addr_i[4] ? _120_[138] : _120_[10];
  assign _121_[11] = req_addr_i[4] ? _120_[139] : _120_[11];
  assign _121_[12] = req_addr_i[4] ? _120_[140] : _120_[12];
  assign _121_[13] = req_addr_i[4] ? _120_[141] : _120_[13];
  assign _121_[14] = req_addr_i[4] ? _120_[142] : _120_[14];
  assign _121_[15] = req_addr_i[4] ? _120_[143] : _120_[15];
  assign _121_[16] = req_addr_i[4] ? _120_[144] : _120_[16];
  assign _121_[17] = req_addr_i[4] ? _120_[145] : _120_[17];
  assign _121_[18] = req_addr_i[4] ? _120_[146] : _120_[18];
  assign _121_[19] = req_addr_i[4] ? _120_[147] : _120_[19];
  assign _121_[20] = req_addr_i[4] ? _120_[148] : _120_[20];
  assign _121_[21] = req_addr_i[4] ? _120_[149] : _120_[21];
  assign _121_[22] = req_addr_i[4] ? _120_[150] : _120_[22];
  assign _121_[23] = req_addr_i[4] ? _120_[151] : _120_[23];
  assign _121_[24] = req_addr_i[4] ? _120_[152] : _120_[24];
  assign _121_[25] = req_addr_i[4] ? _120_[153] : _120_[25];
  assign _121_[26] = req_addr_i[4] ? _120_[154] : _120_[26];
  assign _121_[27] = req_addr_i[4] ? _120_[155] : _120_[27];
  assign _121_[28] = req_addr_i[4] ? _120_[156] : _120_[28];
  assign _121_[29] = req_addr_i[4] ? _120_[157] : _120_[29];
  assign _121_[30] = req_addr_i[4] ? _120_[158] : _120_[30];
  assign _121_[31] = req_addr_i[4] ? _120_[159] : _120_[31];
  assign _121_[256] = req_addr_i[4] ? _120_[384] : _120_[256];
  assign _121_[257] = req_addr_i[4] ? _120_[385] : _120_[257];
  assign _121_[258] = req_addr_i[4] ? _120_[386] : _120_[258];
  assign _121_[259] = req_addr_i[4] ? _120_[387] : _120_[259];
  assign _121_[260] = req_addr_i[4] ? _120_[388] : _120_[260];
  assign _121_[261] = req_addr_i[4] ? _120_[389] : _120_[261];
  assign _121_[262] = req_addr_i[4] ? _120_[390] : _120_[262];
  assign _121_[263] = req_addr_i[4] ? _120_[391] : _120_[263];
  assign _121_[264] = req_addr_i[4] ? _120_[392] : _120_[264];
  assign _121_[265] = req_addr_i[4] ? _120_[393] : _120_[265];
  assign _121_[266] = req_addr_i[4] ? _120_[394] : _120_[266];
  assign _121_[267] = req_addr_i[4] ? _120_[395] : _120_[267];
  assign _121_[268] = req_addr_i[4] ? _120_[396] : _120_[268];
  assign _121_[269] = req_addr_i[4] ? _120_[397] : _120_[269];
  assign _121_[270] = req_addr_i[4] ? _120_[398] : _120_[270];
  assign _121_[271] = req_addr_i[4] ? _120_[399] : _120_[271];
  assign _121_[272] = req_addr_i[4] ? _120_[400] : _120_[272];
  assign _121_[273] = req_addr_i[4] ? _120_[401] : _120_[273];
  assign _121_[274] = req_addr_i[4] ? _120_[402] : _120_[274];
  assign _121_[275] = req_addr_i[4] ? _120_[403] : _120_[275];
  assign _121_[276] = req_addr_i[4] ? _120_[404] : _120_[276];
  assign _121_[277] = req_addr_i[4] ? _120_[405] : _120_[277];
  assign _121_[278] = req_addr_i[4] ? _120_[406] : _120_[278];
  assign _121_[279] = req_addr_i[4] ? _120_[407] : _120_[279];
  assign _121_[280] = req_addr_i[4] ? _120_[408] : _120_[280];
  assign _121_[281] = req_addr_i[4] ? _120_[409] : _120_[281];
  assign _121_[282] = req_addr_i[4] ? _120_[410] : _120_[282];
  assign _121_[283] = req_addr_i[4] ? _120_[411] : _120_[283];
  assign _121_[284] = req_addr_i[4] ? _120_[412] : _120_[284];
  assign _121_[285] = req_addr_i[4] ? _120_[413] : _120_[285];
  assign _121_[286] = req_addr_i[4] ? _120_[414] : _120_[286];
  assign _121_[287] = req_addr_i[4] ? _120_[415] : _120_[287];
  assign _120_[0] = req_addr_i[3] ? sram_dout[64] : sram_dout[0];
  assign _120_[1] = req_addr_i[3] ? sram_dout[65] : sram_dout[1];
  assign _120_[2] = req_addr_i[3] ? sram_dout[66] : sram_dout[2];
  assign _120_[3] = req_addr_i[3] ? sram_dout[67] : sram_dout[3];
  assign _120_[4] = req_addr_i[3] ? sram_dout[68] : sram_dout[4];
  assign _120_[5] = req_addr_i[3] ? sram_dout[69] : sram_dout[5];
  assign _120_[6] = req_addr_i[3] ? sram_dout[70] : sram_dout[6];
  assign _120_[7] = req_addr_i[3] ? sram_dout[71] : sram_dout[7];
  assign _120_[8] = req_addr_i[3] ? sram_dout[72] : sram_dout[8];
  assign _120_[9] = req_addr_i[3] ? sram_dout[73] : sram_dout[9];
  assign _120_[10] = req_addr_i[3] ? sram_dout[74] : sram_dout[10];
  assign _120_[11] = req_addr_i[3] ? sram_dout[75] : sram_dout[11];
  assign _120_[12] = req_addr_i[3] ? sram_dout[76] : sram_dout[12];
  assign _120_[13] = req_addr_i[3] ? sram_dout[77] : sram_dout[13];
  assign _120_[14] = req_addr_i[3] ? sram_dout[78] : sram_dout[14];
  assign _120_[15] = req_addr_i[3] ? sram_dout[79] : sram_dout[15];
  assign _120_[16] = req_addr_i[3] ? sram_dout[80] : sram_dout[16];
  assign _120_[17] = req_addr_i[3] ? sram_dout[81] : sram_dout[17];
  assign _120_[18] = req_addr_i[3] ? sram_dout[82] : sram_dout[18];
  assign _120_[19] = req_addr_i[3] ? sram_dout[83] : sram_dout[19];
  assign _120_[20] = req_addr_i[3] ? sram_dout[84] : sram_dout[20];
  assign _120_[21] = req_addr_i[3] ? sram_dout[85] : sram_dout[21];
  assign _120_[22] = req_addr_i[3] ? sram_dout[86] : sram_dout[22];
  assign _120_[23] = req_addr_i[3] ? sram_dout[87] : sram_dout[23];
  assign _120_[24] = req_addr_i[3] ? sram_dout[88] : sram_dout[24];
  assign _120_[25] = req_addr_i[3] ? sram_dout[89] : sram_dout[25];
  assign _120_[26] = req_addr_i[3] ? sram_dout[90] : sram_dout[26];
  assign _120_[27] = req_addr_i[3] ? sram_dout[91] : sram_dout[27];
  assign _120_[28] = req_addr_i[3] ? sram_dout[92] : sram_dout[28];
  assign _120_[29] = req_addr_i[3] ? sram_dout[93] : sram_dout[29];
  assign _120_[30] = req_addr_i[3] ? sram_dout[94] : sram_dout[30];
  assign _120_[31] = req_addr_i[3] ? sram_dout[95] : sram_dout[31];
  assign _120_[128] = req_addr_i[3] ? sram_dout[192] : sram_dout[128];
  assign _120_[129] = req_addr_i[3] ? sram_dout[193] : sram_dout[129];
  assign _120_[130] = req_addr_i[3] ? sram_dout[194] : sram_dout[130];
  assign _120_[131] = req_addr_i[3] ? sram_dout[195] : sram_dout[131];
  assign _120_[132] = req_addr_i[3] ? sram_dout[196] : sram_dout[132];
  assign _120_[133] = req_addr_i[3] ? sram_dout[197] : sram_dout[133];
  assign _120_[134] = req_addr_i[3] ? sram_dout[198] : sram_dout[134];
  assign _120_[135] = req_addr_i[3] ? sram_dout[199] : sram_dout[135];
  assign _120_[136] = req_addr_i[3] ? sram_dout[200] : sram_dout[136];
  assign _120_[137] = req_addr_i[3] ? sram_dout[201] : sram_dout[137];
  assign _120_[138] = req_addr_i[3] ? sram_dout[202] : sram_dout[138];
  assign _120_[139] = req_addr_i[3] ? sram_dout[203] : sram_dout[139];
  assign _120_[140] = req_addr_i[3] ? sram_dout[204] : sram_dout[140];
  assign _120_[141] = req_addr_i[3] ? sram_dout[205] : sram_dout[141];
  assign _120_[142] = req_addr_i[3] ? sram_dout[206] : sram_dout[142];
  assign _120_[143] = req_addr_i[3] ? sram_dout[207] : sram_dout[143];
  assign _120_[144] = req_addr_i[3] ? sram_dout[208] : sram_dout[144];
  assign _120_[145] = req_addr_i[3] ? sram_dout[209] : sram_dout[145];
  assign _120_[146] = req_addr_i[3] ? sram_dout[210] : sram_dout[146];
  assign _120_[147] = req_addr_i[3] ? sram_dout[211] : sram_dout[147];
  assign _120_[148] = req_addr_i[3] ? sram_dout[212] : sram_dout[148];
  assign _120_[149] = req_addr_i[3] ? sram_dout[213] : sram_dout[149];
  assign _120_[150] = req_addr_i[3] ? sram_dout[214] : sram_dout[150];
  assign _120_[151] = req_addr_i[3] ? sram_dout[215] : sram_dout[151];
  assign _120_[152] = req_addr_i[3] ? sram_dout[216] : sram_dout[152];
  assign _120_[153] = req_addr_i[3] ? sram_dout[217] : sram_dout[153];
  assign _120_[154] = req_addr_i[3] ? sram_dout[218] : sram_dout[154];
  assign _120_[155] = req_addr_i[3] ? sram_dout[219] : sram_dout[155];
  assign _120_[156] = req_addr_i[3] ? sram_dout[220] : sram_dout[156];
  assign _120_[157] = req_addr_i[3] ? sram_dout[221] : sram_dout[157];
  assign _120_[158] = req_addr_i[3] ? sram_dout[222] : sram_dout[158];
  assign _120_[159] = req_addr_i[3] ? sram_dout[223] : sram_dout[159];
  assign _120_[256] = req_addr_i[3] ? sram_dout[320] : sram_dout[256];
  assign _120_[257] = req_addr_i[3] ? sram_dout[321] : sram_dout[257];
  assign _120_[258] = req_addr_i[3] ? sram_dout[322] : sram_dout[258];
  assign _120_[259] = req_addr_i[3] ? sram_dout[323] : sram_dout[259];
  assign _120_[260] = req_addr_i[3] ? sram_dout[324] : sram_dout[260];
  assign _120_[261] = req_addr_i[3] ? sram_dout[325] : sram_dout[261];
  assign _120_[262] = req_addr_i[3] ? sram_dout[326] : sram_dout[262];
  assign _120_[263] = req_addr_i[3] ? sram_dout[327] : sram_dout[263];
  assign _120_[264] = req_addr_i[3] ? sram_dout[328] : sram_dout[264];
  assign _120_[265] = req_addr_i[3] ? sram_dout[329] : sram_dout[265];
  assign _120_[266] = req_addr_i[3] ? sram_dout[330] : sram_dout[266];
  assign _120_[267] = req_addr_i[3] ? sram_dout[331] : sram_dout[267];
  assign _120_[268] = req_addr_i[3] ? sram_dout[332] : sram_dout[268];
  assign _120_[269] = req_addr_i[3] ? sram_dout[333] : sram_dout[269];
  assign _120_[270] = req_addr_i[3] ? sram_dout[334] : sram_dout[270];
  assign _120_[271] = req_addr_i[3] ? sram_dout[335] : sram_dout[271];
  assign _120_[272] = req_addr_i[3] ? sram_dout[336] : sram_dout[272];
  assign _120_[273] = req_addr_i[3] ? sram_dout[337] : sram_dout[273];
  assign _120_[274] = req_addr_i[3] ? sram_dout[338] : sram_dout[274];
  assign _120_[275] = req_addr_i[3] ? sram_dout[339] : sram_dout[275];
  assign _120_[276] = req_addr_i[3] ? sram_dout[340] : sram_dout[276];
  assign _120_[277] = req_addr_i[3] ? sram_dout[341] : sram_dout[277];
  assign _120_[278] = req_addr_i[3] ? sram_dout[342] : sram_dout[278];
  assign _120_[279] = req_addr_i[3] ? sram_dout[343] : sram_dout[279];
  assign _120_[280] = req_addr_i[3] ? sram_dout[344] : sram_dout[280];
  assign _120_[281] = req_addr_i[3] ? sram_dout[345] : sram_dout[281];
  assign _120_[282] = req_addr_i[3] ? sram_dout[346] : sram_dout[282];
  assign _120_[283] = req_addr_i[3] ? sram_dout[347] : sram_dout[283];
  assign _120_[284] = req_addr_i[3] ? sram_dout[348] : sram_dout[284];
  assign _120_[285] = req_addr_i[3] ? sram_dout[349] : sram_dout[285];
  assign _120_[286] = req_addr_i[3] ? sram_dout[350] : sram_dout[286];
  assign _120_[287] = req_addr_i[3] ? sram_dout[351] : sram_dout[287];
  assign _120_[384] = req_addr_i[3] ? sram_dout[448] : sram_dout[384];
  assign _120_[385] = req_addr_i[3] ? sram_dout[449] : sram_dout[385];
  assign _120_[386] = req_addr_i[3] ? sram_dout[450] : sram_dout[386];
  assign _120_[387] = req_addr_i[3] ? sram_dout[451] : sram_dout[387];
  assign _120_[388] = req_addr_i[3] ? sram_dout[452] : sram_dout[388];
  assign _120_[389] = req_addr_i[3] ? sram_dout[453] : sram_dout[389];
  assign _120_[390] = req_addr_i[3] ? sram_dout[454] : sram_dout[390];
  assign _120_[391] = req_addr_i[3] ? sram_dout[455] : sram_dout[391];
  assign _120_[392] = req_addr_i[3] ? sram_dout[456] : sram_dout[392];
  assign _120_[393] = req_addr_i[3] ? sram_dout[457] : sram_dout[393];
  assign _120_[394] = req_addr_i[3] ? sram_dout[458] : sram_dout[394];
  assign _120_[395] = req_addr_i[3] ? sram_dout[459] : sram_dout[395];
  assign _120_[396] = req_addr_i[3] ? sram_dout[460] : sram_dout[396];
  assign _120_[397] = req_addr_i[3] ? sram_dout[461] : sram_dout[397];
  assign _120_[398] = req_addr_i[3] ? sram_dout[462] : sram_dout[398];
  assign _120_[399] = req_addr_i[3] ? sram_dout[463] : sram_dout[399];
  assign _120_[400] = req_addr_i[3] ? sram_dout[464] : sram_dout[400];
  assign _120_[401] = req_addr_i[3] ? sram_dout[465] : sram_dout[401];
  assign _120_[402] = req_addr_i[3] ? sram_dout[466] : sram_dout[402];
  assign _120_[403] = req_addr_i[3] ? sram_dout[467] : sram_dout[403];
  assign _120_[404] = req_addr_i[3] ? sram_dout[468] : sram_dout[404];
  assign _120_[405] = req_addr_i[3] ? sram_dout[469] : sram_dout[405];
  assign _120_[406] = req_addr_i[3] ? sram_dout[470] : sram_dout[406];
  assign _120_[407] = req_addr_i[3] ? sram_dout[471] : sram_dout[407];
  assign _120_[408] = req_addr_i[3] ? sram_dout[472] : sram_dout[408];
  assign _120_[409] = req_addr_i[3] ? sram_dout[473] : sram_dout[409];
  assign _120_[410] = req_addr_i[3] ? sram_dout[474] : sram_dout[410];
  assign _120_[411] = req_addr_i[3] ? sram_dout[475] : sram_dout[411];
  assign _120_[412] = req_addr_i[3] ? sram_dout[476] : sram_dout[412];
  assign _120_[413] = req_addr_i[3] ? sram_dout[477] : sram_dout[413];
  assign _120_[414] = req_addr_i[3] ? sram_dout[478] : sram_dout[414];
  assign _120_[415] = req_addr_i[3] ? sram_dout[479] : sram_dout[415];
  assign _107_ = _006_ ? _105_[1] : 1'hx;
  assign next_state[0] = _119_ ? _117_[0] : 1'h0;
  assign next_state[1] = _119_ ? _117_[1] : 1'h0;
  assign next_state[2] = _119_ ? _117_[2] : 1'h0;
  assign _000_[0] = _104_ ? 1'hx : hit_word_data[0];
  assign _000_[1] = _104_ ? 1'hx : hit_word_data[1];
  assign _000_[2] = _104_ ? 1'hx : hit_word_data[2];
  assign _000_[3] = _104_ ? 1'hx : hit_word_data[3];
  assign _000_[4] = _104_ ? 1'hx : hit_word_data[4];
  assign _000_[5] = _104_ ? 1'hx : hit_word_data[5];
  assign _000_[6] = _104_ ? 1'hx : hit_word_data[6];
  assign _000_[7] = _104_ ? 1'hx : hit_word_data[7];
  assign _000_[8] = _104_ ? 1'hx : hit_word_data[8];
  assign _000_[9] = _104_ ? 1'hx : hit_word_data[9];
  assign _000_[10] = _104_ ? 1'hx : hit_word_data[10];
  assign _000_[11] = _104_ ? 1'hx : hit_word_data[11];
  assign _000_[12] = _104_ ? 1'hx : hit_word_data[12];
  assign _000_[13] = _104_ ? 1'hx : hit_word_data[13];
  assign _000_[14] = _104_ ? 1'hx : hit_word_data[14];
  assign _000_[15] = _104_ ? 1'hx : hit_word_data[15];
  assign _000_[16] = _104_ ? 1'hx : hit_word_data[16];
  assign _000_[17] = _104_ ? 1'hx : hit_word_data[17];
  assign _000_[18] = _104_ ? 1'hx : hit_word_data[18];
  assign _000_[19] = _104_ ? 1'hx : hit_word_data[19];
  assign _000_[20] = _104_ ? 1'hx : hit_word_data[20];
  assign _000_[21] = _104_ ? 1'hx : hit_word_data[21];
  assign _000_[22] = _104_ ? 1'hx : hit_word_data[22];
  assign _000_[23] = _104_ ? 1'hx : hit_word_data[23];
  assign _000_[24] = _104_ ? 1'hx : hit_word_data[24];
  assign _000_[25] = _104_ ? 1'hx : hit_word_data[25];
  assign _000_[26] = _104_ ? 1'hx : hit_word_data[26];
  assign _000_[27] = _104_ ? 1'hx : hit_word_data[27];
  assign _000_[28] = _104_ ? 1'hx : hit_word_data[28];
  assign _000_[29] = _104_ ? 1'hx : hit_word_data[29];
  assign _000_[30] = _104_ ? 1'hx : hit_word_data[30];
  assign _000_[31] = _104_ ? 1'hx : hit_word_data[31];
  assign _108_[0] = resp_ready_i ? 1'h0 : 1'hx;
  assign _115_[7] = l2_resp_valid_i ? 1'h1 : 1'hx;
  assign _115_[8] = l2_resp_valid_i ? 1'h0 : 1'hx;
  assign _115_[11] = l2_req_ready_i ? 1'h0 : 1'hx;
  assign _115_[10] = l2_req_ready_i ? 1'h1 : 1'hx;
  assign _115_[12] = req_valid_i ? 1'h1 : 1'hx;
  assign _115_[14] = req_valid_i ? 1'h0 : 1'hx;
  assign _001_[0] = flush_i ? 1'h0 : next_state[0];
  assign _001_[1] = flush_i ? 1'h0 : next_state[1];
  assign _001_[2] = flush_i ? 1'h0 : next_state[2];
  assign _114_ = _007_ ? _110_[2] : 1'hx;
  assign _111_ = _118_ ? _112_ : 1'hx;
  assign hit_word_data[0] = req_addr_i[5] ? _121_[256] : _121_[0];
  assign hit_word_data[1] = req_addr_i[5] ? _121_[257] : _121_[1];
  assign hit_word_data[2] = req_addr_i[5] ? _121_[258] : _121_[2];
  assign hit_word_data[3] = req_addr_i[5] ? _121_[259] : _121_[3];
  assign hit_word_data[4] = req_addr_i[5] ? _121_[260] : _121_[4];
  assign hit_word_data[5] = req_addr_i[5] ? _121_[261] : _121_[5];
  assign hit_word_data[6] = req_addr_i[5] ? _121_[262] : _121_[6];
  assign hit_word_data[7] = req_addr_i[5] ? _121_[263] : _121_[7];
  assign hit_word_data[8] = req_addr_i[5] ? _121_[264] : _121_[8];
  assign hit_word_data[9] = req_addr_i[5] ? _121_[265] : _121_[9];
  assign hit_word_data[10] = req_addr_i[5] ? _121_[266] : _121_[10];
  assign hit_word_data[11] = req_addr_i[5] ? _121_[267] : _121_[11];
  assign hit_word_data[12] = req_addr_i[5] ? _121_[268] : _121_[12];
  assign hit_word_data[13] = req_addr_i[5] ? _121_[269] : _121_[13];
  assign hit_word_data[14] = req_addr_i[5] ? _121_[270] : _121_[14];
  assign hit_word_data[15] = req_addr_i[5] ? _121_[271] : _121_[15];
  assign hit_word_data[16] = req_addr_i[5] ? _121_[272] : _121_[16];
  assign hit_word_data[17] = req_addr_i[5] ? _121_[273] : _121_[17];
  assign hit_word_data[18] = req_addr_i[5] ? _121_[274] : _121_[18];
  assign hit_word_data[19] = req_addr_i[5] ? _121_[275] : _121_[19];
  assign hit_word_data[20] = req_addr_i[5] ? _121_[276] : _121_[20];
  assign hit_word_data[21] = req_addr_i[5] ? _121_[277] : _121_[21];
  assign hit_word_data[22] = req_addr_i[5] ? _121_[278] : _121_[22];
  assign hit_word_data[23] = req_addr_i[5] ? _121_[279] : _121_[23];
  assign hit_word_data[24] = req_addr_i[5] ? _121_[280] : _121_[24];
  assign hit_word_data[25] = req_addr_i[5] ? _121_[281] : _121_[25];
  assign hit_word_data[26] = req_addr_i[5] ? _121_[282] : _121_[26];
  assign hit_word_data[27] = req_addr_i[5] ? _121_[283] : _121_[27];
  assign hit_word_data[28] = req_addr_i[5] ? _121_[284] : _121_[28];
  assign hit_word_data[29] = req_addr_i[5] ? _121_[285] : _121_[29];
  assign hit_word_data[30] = req_addr_i[5] ? _121_[286] : _121_[30];
  assign hit_word_data[31] = req_addr_i[5] ? _121_[287] : _121_[31];
  assign _109_[0] = _108_[0] & _110_[0];
  assign _116_[12] = _115_[12] & _110_[2];
  assign _116_[14] = _115_[14] & _110_[2];
  assign _116_[11] = _115_[11] & _113_[0];
  assign _116_[10] = _115_[10] & _113_[0];
  assign _116_[7] = _115_[7] & _105_[1];
  assign _116_[8] = _115_[8] & _105_[1];
  sram_l1_icache_way \gen_ways[0].gen_words[0].sram_inst  (
    .addr0(req_addr_i[12:6]),
    .clk0(clk),
    .csb0(1'h0),
    .din0(64'h0000000000000000),
    .dout0(sram_dout[63:0]),
    .web0(1'h1),
    .wmask0(8'hff)
  );
  sram_l1_icache_way \gen_ways[0].gen_words[1].sram_inst  (
    .addr0(req_addr_i[12:6]),
    .clk0(clk),
    .csb0(1'h0),
    .din0(64'h0000000000000000),
    .dout0(sram_dout[127:64]),
    .web0(1'h1),
    .wmask0(8'hff)
  );
  sram_l1_icache_way \gen_ways[0].gen_words[2].sram_inst  (
    .addr0(req_addr_i[12:6]),
    .clk0(clk),
    .csb0(1'h0),
    .din0(64'h0000000000000000),
    .dout0(sram_dout[191:128]),
    .web0(1'h1),
    .wmask0(8'hff)
  );
  sram_l1_icache_way \gen_ways[0].gen_words[3].sram_inst  (
    .addr0(req_addr_i[12:6]),
    .clk0(clk),
    .csb0(1'h0),
    .din0(64'h0000000000000000),
    .dout0(sram_dout[255:192]),
    .web0(1'h1),
    .wmask0(8'hff)
  );
  sram_l1_icache_way \gen_ways[0].gen_words[4].sram_inst  (
    .addr0(req_addr_i[12:6]),
    .clk0(clk),
    .csb0(1'h0),
    .din0(64'h0000000000000000),
    .dout0(sram_dout[319:256]),
    .web0(1'h1),
    .wmask0(8'hff)
  );
  sram_l1_icache_way \gen_ways[0].gen_words[5].sram_inst  (
    .addr0(req_addr_i[12:6]),
    .clk0(clk),
    .csb0(1'h0),
    .din0(64'h0000000000000000),
    .dout0(sram_dout[383:320]),
    .web0(1'h1),
    .wmask0(8'hff)
  );
  sram_l1_icache_way \gen_ways[0].gen_words[6].sram_inst  (
    .addr0(req_addr_i[12:6]),
    .clk0(clk),
    .csb0(1'h0),
    .din0(64'h0000000000000000),
    .dout0(sram_dout[447:384]),
    .web0(1'h1),
    .wmask0(8'hff)
  );
  sram_l1_icache_way \gen_ways[0].gen_words[7].sram_inst  (
    .addr0(req_addr_i[12:6]),
    .clk0(clk),
    .csb0(1'h0),
    .din0(64'h0000000000000000),
    .dout0(sram_dout[511:448]),
    .web0(1'h1),
    .wmask0(8'hff)
  );
  assign _098_[0] = _109_[0];
  assign _100_[0] = _109_[0];
  assign _102_[0] = _112_;
  assign _105_[0] = 1'h0;
  assign _106_[1] = _105_[1];
  assign _108_[2:1] = 2'h1;
  assign _109_[2:1] = { 1'h0, _106_[0] };
  assign _110_[1] = _106_[0];
  assign _113_[1] = _110_[2];
  assign { _115_[13], _115_[9], _115_[6:0] } = { _115_[14], _115_[11], _115_[7], 3'h4, _108_[0], _108_[0], _108_[0] };
  assign { _116_[13], _116_[9], _116_[6:0] } = { _116_[14], _116_[11], _116_[7], _106_[0], 2'h0, _109_[0], _109_[0], _109_[0] };
  assign _120_[6143:2048] = 4096'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign _121_[6143:2048] = 4096'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign l2_req_addr_o[5:0] = 6'h00;
  assign resp_error_o = 1'h0;
endmodule
